- miasm2/arch/arm/ira.py
- miasm2/core/graph.py
- miasm2/ir/analysis.py
- miasm2/ir/ir.py
Support liveness analysis in incomplete execution flow graph.
> Improve liveness analysis

- miasm2/expression/expression.py
Put parenthesis in ExprCond output
> Expression: fix ExprCond output

- miasm2/core/graph.py
- test/core/graph.py
Add dominator computation
(see https://en.wikipedia.org/wiki/Dominator_(graph_theory))
> Graph: add dominators computation

- miasm2/arch/arm/arch.py
- test/arch/arm/arch.py
umull, smull, smull and smlal are there, but not umlal
(unsigned multiply and accumulate long)
> arm: Add instruction umlal

- miasm2/arch/arm/arch.py
- miasm2/arch/mips32/arch.py
- miasm2/arch/msp430/arch.py
- miasm2/arch/x86/arch.py
Do execflow tests using a white list
> Arm: fix execflow code

- miasm2/analysis/sandbox.py
- miasm2/arch/arm/jit.py
- miasm2/arch/x86/jit.py
- miasm2/jitter/jitload.py
- miasm2/os_dep/win_api_x86_32.py
This PR remove os_dep references in Arch/Jit
The jitter is modified to handle function dynamically  imported.
> Api lib handler

- example/samples/x86_32_pop_esp.S
- miasm2/arch/x86/sem.py
- test/test_all.py
Fixes bug #53 on  `POP ESP` based on intel doc.
> Fix x86 pop esp

- miasm2/arch/x86/arch.py
Fix `breakflow` bug introduced in 49300708f13622595c3cc147a03b6c7848da195d for arch x86.
> X86 breakflow fix

- miasm2/arch/x86/sem.py
FPU semantic is updated according to API
> X86/sem: fix fpu mnemonic api

- miasm2/jitter/loader/pe.py
Fix typo in the PE loader.
Fix section size computation in PE loader
> Fix loader

- miasm2/analysis/sandbox.py
> Sandbox: quiet logs

- miasm2/expression/simplifications_common.py
- test/expression/simplifications.py
Shift operation on `ExprCompose` is applied on Compose arguments.
> Expr simp op compose

- example/jitter/sandbox_pe_x86_64.py
- miasm2/analysis/sandbox.py
Add sandbox/win for x86_64 architecture.
> Sandbox win x86 64

- miasm2/arch/x86/sem.py
> X86: add movqu

- miasm2/analysis/binary.py
- miasm2/analysis/data_analysis.py
- miasm2/analysis/disasm_cb.py
- miasm2/ir/analysis.py
- miasm2/ir/ir2C.py
- miasm2/ir/symbexec.py
- miasm2/os_dep/common.py
- miasm2/os_dep/win_api_x86_32.py
- miasm2/os_dep/win_api_x86_32_seh.py
This PR replaces wildcard imports from some parts of Miasm.
> Replace some wildcard imports

- miasm2/arch/x86/sem.py
- miasm2/ir/translators/C.py
- miasm2/jitter/vm_mngr.c
- test/ir/ir2C.py
- test/samples/x86_32/bsr_bsf.S
- test/test_all.py
Fix behaviour of bsf/bsr for PR #79.
> Fix bsr bsf

- miasm2/os_dep/linux_stdlib.py
This tiny PR is the last step to complete the work started in #73.
> Use named arguments in os_dep/linux

- miasm2/arch/msp430/sem.py
> msp430 semantic: fix carry and overflow flags for cmp.* mnemonics

- miasm2/arch/x86/arch.py
- test/arch/x86/arch.py
Add stmxcsr/ldmxcsr and regression tests.
Fixes Issue  #96
> X86/arch: add stmxcsr/ldmxcsr

- miasm2/ir/ir.py
`get_modified_slice` can send back multiple identical slices.
Those slices need to be factorised for next steps.
> IR: factor identical slices in multi dst effects

- miasm2/arch/msp430/sem.py
> MSP430 semantic: fix SR affectation

- miasm2/ir/analysis.py
- miasm2/ir/ir.py
Avoid dummy line creation for IN/OUT.
Fix not in syntax
> Analysis fix in out

- miasm2/core/asmbloc.py
Start big cleanup in `asmbloc`
* create `AsmBlockLink` to manage links between blocs
* clean asm_symbol_pool
> Asmbloc: clean symbol_pool

- README.md
Add a Travis tag indicating the build status for `master`.
> README: travis tag

- miasm2/core/graph.py
This PR refactors internal structures of `DiGraph`.
The comparison in `add_uniq_edge` is no more an all edges, but only on edges beginning with the same `src`.
For the sample `python symbol_exec/depgraph.py samples/simple_test.bin -i --rename-args -m x86_32 0x0 0x8B eax `, this leads to 1.5s instead of 7s of execution time.
> Enhance graph

- miasm2/expression/expression.py
- miasm2/ir/analysis.py
- miasm2/ir/ir.py
- test/ir/analysis.py
- test/test_all.py
Dead code analysis computed using Ken Kennedy Algorithm
Ref: A survey of data flow analysis techniques, IBM Thomas
J. Watson Research Division, 1979
> IR: Improve dead code elimination

- miasm2/analysis/depgraph.py
- miasm2/ir/analysis.py
fixed typos, replaced redundant code and removed unused code
> Minor fixes

- example/expression/graph_dataflow.py
- test/test_all.py
From #156 , one of the example (`graph_dataflow`) was only covered by 55%. Actually, a function was never called.
This PR refactors this example and add an option to switch and called the forgotten feature.
> Enhance graphdataflow

- miasm2/core/graph.py
- test/core/graph.py
Add walk_dominator/walk_postdominator in graph
> Walk dominator

- miasm2/core/graph.py
- test/core/graph.py
graph.py: extend DiGraph with implementations for computation of immediate dominators and dominance frontier
> Extend digraph

- example/disasm/full.py
- miasm2/arch/msp430/arch.py
Two trivial commits having a glance at the code. Should be self explanatory ;-)
Cheers !
> typofix and logic error

- miasm2/os_dep/common.py
- miasm2/os_dep/win_api_x86_32.py
This PR also includes PEP8 compliance fixes in a separated commit.
> Factorize code to handle sandboxed files

- miasm2/analysis/sandbox.py
Hi,
I wondered why a linux 64 sandbox doesn't exist, so I pushed it.
> sandbox: added sandbox for Linux_x86_64

- README.md
Add a code-climate badge, allowing us to track an indicator on the code quality over commits, and signal it to new users.
> README: add a code-climate badge

- miasm2/ir/translators/C.py
- test/ir/ir2C.py
> IR/Translators/C: fix umod/udiv argument

- miasm2/analysis/depgraph.py
- test/analysis/depgraph.py
This PR improves the DependencyGraph algorithm :  in the analysis, when two parrallel expressions depend on the same variable, only one DependencyNode is created.
> Dependency graph

- miasm2/analysis/depgraph.py
Improve `depgraph` modifier complexity
> Depgraph modifier

- miasm2/arch/aarch64/arch.py
- test/arch/aarch64/arch.py
Fixes some instructions which manipulates ZR.
> Fix aarchzr

- miasm2/core/graph.py
- test/core/graph.py
Part of this PR:
- search-first walks
- natural loop detection
- strongly connected components detection
> Extend digraph with loop detection algorithms

- miasm2/analysis/depgraph.py
Fix misbehavior between `follow_mem/follow_call`
> Fix follow expr

- miasm2/ir/ir.py
Publish useful internal methods
> IR: add get_label

- test/test_all.py
This PR removes residual tests outputs.
> Fix test deletion

- miasm2/arch/aarch64/arch.py
- test/arch/aarch64/arch.py
Fix `ANDS` destination (`ZR` instead of `SP`)
> Fix aarch64

- miasm2/ir/translators/z3_ir.py
Added translations for ```<<<``` and ```>>>```.
> TranslatorZ3: added translation for left and right rotation

- miasm2/jitter/jitcore_tcc.py
While there, make all imports in that file homogeneous.
Thanks to @commial for his comments.
> Use path relative to miasm2 rather than local dir for Jittcc

- miasm2/analysis/sandbox.py
- miasm2/jitter/vm_mngr_py.c
- miasm2/os_dep/win_api_x86_32_seh.py
Limit structures generated by the `SEH` handler to avoid inserting dummy padding
> Win seh alloc min

- miasm2/core/sembuilder.py
Fixes #240 .
According to `ast.NodeTransformer` docstring:
*Keep in mind that if the node you're operating on has child nodes you must either transform the child nodes yourself or call the :meth:`generic_visit` method for the node first.*
> SemBuilder: fix recursive visit

- miasm2/core/asmbloc.py
> Core/asmbloc: Fix get_subcall_instr

- example/asm/shellcode.py
- example/asm/simple.py
- example/expression/asm_to_ir.py
- example/expression/expr_grapher.py
- example/expression/simplification_tools.py
- example/expression/solve_condition_stp.py
- example/ida/depgraph.py
- example/ida/graph_ir.py
- example/jitter/arm_sc.py
- example/jitter/mips32.py
- example/jitter/msp430.py
Fix unused imports in examples.
> Unused import

- example/asm/shellcode.py
- example/disasm/file.py
- example/disasm/full.py
- example/disasm/function.py
- example/expression/asm_to_ir.py
- example/expression/get_read_write.py
- example/expression/graph_dataflow.py
- example/expression/solve_condition_stp.py
- example/ida/graph_ir.py
- example/jitter/unpack_upx.py
- test/test_all.py
As Miasm graphics outputs are in `dot` format, use `.dot` instead of `.txt`
> Extension dot

- miasm2/os_dep/win_api_x86_32_seh.py
This PR fixes modules entries in the loader data emulation.
> Fix module list

- miasm2/ir/translators/C.py
- miasm2/jitter/vm_mngr.c
- miasm2/jitter/vm_mngr.h
- miasm2/jitter/vm_mngr_py.c
- test/ir/ir2C.py
* Use dichotomie to search memory pool
* remove unused div/rem op
* global cealning
> Jit bin search clean

- example/jitter/unpack_upx.py
- miasm2/analysis/sandbox.py
- miasm2/jitter/loader/pe.py
- miasm2/jitter/loader/utils.py
- miasm2/os_dep/win_api_x86_32_seh.py
* Cleanup in win_seh code
* Add load dependencies options
* Propagate kwargs in loader; default don't parse ressources
* Default hcurmodule
> Updt winseh

- example/jitter/unpack_upx.py
- miasm2/analysis/sandbox.py
Some options were no longer used in Windows sandboxes.
> Fix sandbox options

- example/asm/shellcode.py
- example/jitter/unpack_upx.py
- miasm2/core/bin_stream.py
- miasm2/jitter/loader/elf.py
- miasm2/jitter/loader/pe.py
:warning: This PR needs ELFESTEEM serpilliere/elfesteem@837b05affa09b2095877ad6801be82c2db557d45 update!!
> Update api according to Elfesteem

- miasm2/jitter/loader/pe.py
Add support for r/w/rw pages in pe loader
> Loader/pe: fix load page rw

- miasm2/core/asmbloc.py
- miasm2/ir/ir.py
* Asserts block label is `asm_label`
* fix `get_range` hull
> Fix asmbloc

- miasm2/analysis/binary.py
- miasm2/analysis/sandbox.py
- miasm2/core/asmbloc.py
- miasm2/core/bin_stream_ida.py
- miasm2/core/cpu.py
- miasm2/core/graph.py
- miasm2/core/parse_asm.py
- miasm2/core/types.py
- miasm2/ir/ir.py
- miasm2/ir/ir2C.py
- miasm2/jitter/loader/pe.py
- miasm2/os_dep/win_api_x86_32.py
Remove some unused variable / clean code
> Unused variable

- miasm2/arch/x86/sem.py
- miasm2/ir/translators/C.py
- miasm2/ir/translators/smt2.py
- miasm2/ir/translators/z3_ir.py
Thanks to @a-vincent for reporting shl/sal dup instruction.
> X86 sal shl

- miasm2/ir/translators/__init__.py
- miasm2/ir/translators/smt2.py
* fixed smt translator registration
* added flag for model model generation
> Fix smt2translator

- miasm2/core/asmbloc.py
- test/core/asmbloc.py
Fixes double block splitting bug.
Thanks to @commial and @fmonjalet
> Asmcfg pending

- miasm2/os_dep/win_api_x86_32_seh.py
Fixes invalid link list entry in the loader structure.
> OS_Dep/Win_seh: fix link list entries

- miasm2/analysis/depgraph.py
- miasm2/core/graph.py
- test/analysis/dg_test_06_expected.json
- test/analysis/dg_test_06_implicit_expected.json
Add loop detection algorithm to the graph class.
Update `DependencyResult` to use this algorithm.
Thanks to @carolineLe for the loop detection algorithm
> Dg has loop

- miasm2/jitter/vm_mngr.c
- miasm2/jitter/vm_mngr.h
- miasm2/jitter/vm_mngr_py.c
* fix `find_page_node` of last page search
* add api `is_mapped`
> Fix find page; Add is_mapped

- example/ida/depgraph.py
Add function's argument tracking in depgraph IDA plugin.
* set cursor on the `call` line
* use ARG0 for tracking arg0, ARG1 for arg1, ...
The stack height is resolved using IDA `GetSpd` heuristic.
> Example/ida/depgraph: add basic stack unaliasing

- miasm2/jitter/jitcore_gcc.py
> Jitter/gcc: fit fd leak

- miasm2/arch/x86/arch.py
- test/arch/x86/arch.py
Just a bunch of opcodes that aren't in the decoding
> some X86 opcodes decodings

- miasm2/arch/x86/sem.py
x86 sem: prefetchw, ud2 and lfence added
> x86 sem: prefetchw, ud2 and lfence added

- miasm2/os_dep/win_32_structs.py
- miasm2/os_dep/win_api_x86_32_seh.py
This PR adds windows structures description using `MemStruct`.
The code is update in consequence.
The default `seh` location mimics windows.
Note:
The current todo stay un modified in this PR.
> Win seh struct

- miasm2/expression/simplifications_cond.py
- test/expression/simplifications.py
Based on #386.
Fix #385 
(credits: @jbcayrou)
> Fix ExprOp_inf_signed + unit tests #385

- miasm2/jitter/vm_mngr_py.c
- test/jitter/vm_mngr_py.c.py
- test/test_all.py
Add get_mem_access function to miasm2/jitter/vm_mngr_py.c and its corresponding test cases in test/vm_mngr_py.c.py
> Add a way to retrieve memory access right

- miasm2/arch/x86/regs.py
Here is a small PR that removes duplicated R15* declaration.
> The R15 register is declared multiple times

- example/expression/simplification_add.py
- example/expression/solve_condition_stp.py
- example/ida/depgraph.py
- miasm2/arch/aarch64/arch.py
- miasm2/arch/aarch64/sem.py
- miasm2/arch/arm/arch.py
- miasm2/arch/arm/sem.py
- miasm2/arch/msp430/sem.py
- miasm2/arch/x86/arch.py
- miasm2/arch/x86/sem.py
- miasm2/core/asmbloc.py
- miasm2/core/cpu.py
- miasm2/expression/expression.py
- miasm2/expression/simplifications_common.py
- miasm2/ir/ir.py
- miasm2/ir/symbexec.py
- test/arch/arm/sem.py
- test/arch/msp430/sem.py
- test/arch/x86/sem.py
Replace `isintance(expr, ExprIn)` by `expr.is_int()`
Code cleanup
> Add expr type access

- miasm2/analysis/depgraph.py
> DepGraph: clean step

- miasm2/arch/aarch64/ira.py
- miasm2/arch/arm/ira.py
- miasm2/arch/mips32/ira.py
- miasm2/arch/msp430/ira.py
- miasm2/arch/x86/ira.py
- miasm2/ir/analysis.py
- miasm2/ir/ir.py
* Add 'instr' to 'call_effects'
* do not stack ret addr in x86 default subcall model
> Updt call effects api

- miasm2/analysis/depgraph.py
- test/analysis/dg_test_11_expected.json
- test/analysis/dg_test_11_implicit_expected.json
- test/samples/x86_32/dg_test_11.S
- test/test_all.py
Fix depgraph result emulation in some corner cases.
Add regression tests.
> Fix dg emul

- miasm2/jitter/codegen.py
- miasm2/jitter/llvmconvert.py
- test/jitter/jit_options.py
> Fix max exec self loop

- miasm2/jitter/jitload.py
- miasm2/jitter/vm_mngr.c
- miasm2/jitter/vm_mngr_py.c
> Doc vmmngr

- .travis.yml
Fix the version of LLVMLite (there are issues while installing llvm-3.9 on travis in precise)
> Update LLVM version for latest llvmlite

- README.md
Add a reference to @guedou's project [R2M2](https://github.com/guedou/r2m2)
> Add reference to R2M2

- miasm2/jitter/emulatedsymbexec.py
Add `cpuid` support in Python emulation
> Add support for 'cpuid' in Emulatedsymbexec

- README.md
Do not hesitate to add pointers in comments, I will add them.
Theses references highlight some Miasm uses, in different condition, not necessarily covered by the [blog](http://miasm.re)
> Update external references to Miasm

- miasm2/arch/mips32/sem.py
*init*
mips32l  
cpu.GP=0x7de8  
*code*
'\x18\x82\x82\x23'   
*emulate result*
cpu.V0==0
> add mips32's addi simulation

- miasm2/ir/ir.py
Fix tipo in old `blocs` api support
> IR: fix support old api blocs

- example/disasm/full.py
- example/expression/asm_to_ir.py
- example/expression/graph_dataflow.py
- example/ida/graph_ir.py
- miasm2/analysis/data_flow.py
- miasm2/ir/analysis.py
- test/analysis/data_flow.py
- test/test_all.py
- previous dead_simp function has been moved to data_flow.py
- ira class has been simplified
- reach analysis code has been 'clarified'
> analysis: Introduction of use-definition chains

- miasm2/jitter/vm_mngr_py.c
Bug raised with @commial 
Thanks!
> Jitter: fix pending memory breakpoint

- example/expression/access_c.py
- example/symbol_exec/depgraph.py
- miasm2/analysis/data_flow.py
- miasm2/analysis/depgraph.py
- miasm2/arch/aarch64/sem.py
- miasm2/arch/mips32/ira.py
- miasm2/arch/mips32/jit.py
- miasm2/arch/x86/ira.py
- miasm2/arch/x86/sem.py
- miasm2/ir/analysis.py
- miasm2/ir/ir.py
- miasm2/jitter/codegen.py
- miasm2/jitter/jitcore_python.py
- miasm2/jitter/llvmconvert.py
- test/analysis/data_flow.py
- test/analysis/depgraph.py
- test/ir/symbexec.py
PR done with @commial 
Thanks!
> Assignblock ro

- miasm2/arch/x86/jit.py
- miasm2/arch/x86/sem.py
- test/arch/x86/unit/mn_pushpop.py
Sanitize/Fix some x86 semantic opcodes
> Fix x86 segm

- miasm2/expression/simplifications_common.py
- test/expression/simplifications.py
`{@X[base + i] 0 X, @Y[base + i + X] X (X + Y)} => @(X+Y)[base + i]`
> Add a new simplification merging ExprMem sharing the same base in ExprCompose

- example/ida/ctype_propagation.py
- miasm2/core/ctypesmngr.py
- miasm2/expression/parser.py
- miasm2/ir/symbexec.py
- miasm2/ir/symbexec_top.py
- miasm2/ir/symbexec_types.py
- miasm2/jitter/emulatedsymbexec.py
- test/expression/parser.py
- test/test_all.py
Add C type propagation engine
Add corresponding IDA plugin
> Exec engine

- miasm2/ir/translators/C.py
- miasm2/jitter/vm_mngr.c
- miasm2/jitter/vm_mngr.h
Thanks to @WilliamBruneau  for bug hunting and @a-vincent for macro tips
> Jitter: fix shifter macro

- miasm2/expression/simplifications.py
- miasm2/expression/simplifications_common.py
- test/expression/simplifications.py
Some expression simplifier cleanning.
> Add reductions

- miasm2/arch/x86/sem.py
- miasm2/expression/expression.py
Adding instruction ucomisd by copying and adapting ucomiss.
> Adding ucomisd

- miasm2/jitter/Jittcc.c
@mkrzywix if you are ok with this, I merge this commit part
> Jitter: remove french debug string

- example/disasm/full.py
- example/jitter/msp430.py
- example/jitter/sandbox_call.py
- example/symbol_exec/depgraph.py
- example/symbol_exec/dse_crackme.py
- miasm2/analysis/sandbox.py
- miasm2/jitter/jitcore_tcc.py
- miasm2/jitter/llvmconvert.py
- miasm2/jitter/loader/pe.py
Python on Windows makes a distinction between text and binary files
@w4kfu: if you are ok with this, I merge this commit part!
> Append b to the opens mode

- miasm2/arch/x86/arch.py
- miasm2/arch/x86/regs.py
- miasm2/arch/x86/sem.py
- test/arch/x86/arch.py
This PR adds:
* basic support for BND registers
* BNDMOV (as a NOP because BND restrictions are not supported)
* PALIGNR
* PSRLDQ
* PCMPGTB
* PREFETCHNTA (as a NOP, like the others PREFETCHs)
> Add a few SSE instructions

- miasm2/arch/ppc/sem.py
> Fix semantics of conditional jumps

- example/expression/graph_dataflow.py
- example/expression/solve_condition_stp.py
- example/ida/ctype_propagation.py
- example/ida/symbol_exec.py
- example/symbol_exec/single_instr.py
- miasm2/analysis/cst_propag.py
- miasm2/analysis/depgraph.py
- miasm2/analysis/dse.py
- miasm2/arch/aarch64/sem.py
- miasm2/arch/arm/sem.py
- miasm2/arch/mips32/sem.py
- miasm2/arch/msp430/sem.py
- miasm2/ir/symbexec.py
- miasm2/ir/symbexec_top.py
- miasm2/ir/symbexec_types.py
- miasm2/jitter/jitcore_python.py
- miasm2/jitter/jitload.py
- test/arch/arm/sem.py
- test/arch/msp430/sem.py
- test/arch/x86/sem.py
- test/ir/symbexec.py
Update SymbolicExecutionEngine APIs.
> Symbexec: use hashtable for mem symbols

- miasm2/analysis/dse.py
> DSE: update doc on attachment in a breakpoint

- miasm2/core/asmblock.py
- miasm2/jitter/jitcore.py
- test/jitter/bad_block.py
- test/jitter/jmp_out_mem.py
- test/jitter/test_post_instr.py
- test/test_all.py
Fix asmblockbad handling in jitter
> Asmblobk bad jit

- miasm2/arch/aarch64/sem.py
adding the semantics for ccmp instruction in aarch64 architecture.
> Adding ccmp aarch64 instruction.

- miasm2/arch/arm/arch.py
- miasm2/arch/arm/ira.py
- miasm2/core/cpu.py
- test/arch/arm/arch.py
Change armtl code use to branch when offset is larger than expected
Change armtl code use to branch when offset is negative
> armtl change branch pc offset

- miasm2/arch/arm/regs.py
- miasm2/arch/arm/sem.py
- miasm2/jitter/arch/JitCore_arm.c
- miasm2/jitter/arch/JitCore_arm.h
This is mainly done by copy-pasting things from the X86 "int" implementation. It looks like some of these stuff could be factorized. Do you want me to try something like that?
It also misses one test I need to polish.
FTR I used it in a recent study, and it worked in this case!
> Support of ARM SVC in the Miasm VM

- example/ida/ctype_propagation.py
- miasm2/arch/arm/arch.py
- miasm2/arch/arm/ira.py
- miasm2/arch/mips32/ira.py
- miasm2/arch/ppc/ira.py
- miasm2/arch/x86/ira.py
- miasm2/ir/analysis.py
This adds the support of IR generation for instructions like:
```
BLNE XXX
```
> Fix call effects arm

- miasm2/analysis/data_flow.py
- test/ir/reduce_graph.py
- infinite loop
- bad block ref
> Fix graph reduce

- example/disasm/full.py
- miasm2/analysis/data_flow.py
- miasm2/analysis/depgraph.py
- miasm2/analysis/ssa.py
- miasm2/arch/aarch64/arch.py
- miasm2/arch/aarch64/regs.py
- miasm2/arch/aarch64/sem.py
- miasm2/arch/arm/jit.py
- miasm2/arch/arm/sem.py
- miasm2/arch/mep/arch.py
- miasm2/arch/x86/sem.py
- miasm2/core/graph.py
- miasm2/expression/expression.py
- miasm2/expression/simplifications.py
- miasm2/expression/simplifications_common.py
- miasm2/expression/simplifications_explicit.py
- miasm2/ir/ir.py
- miasm2/ir/symbexec.py
- miasm2/ir/translators/C.py
- miasm2/ir/translators/z3_ir.py
- miasm2/jitter/codegen.py
- miasm2/jitter/jitcore_python.py
- miasm2/jitter/llvmconvert.py
- test/arch/arm/sem.py
- test/expression/simplifications.py
- test/test_all.py
New features:
- high level operators
- expression propagation
> Operator high level

- miasm2/arch/x86/arch.py
- test/arch/x86/arch.py
> X86: add nop form

- README.md
I messed up and lost the origin link to the appveyor badge :/
> Readme: fix appveyor badge

- miasm2/analysis/data_flow.py
Note: I will add regression tests calling -p after fixing un ssa in order to add code coverage.
> ExprMem: fix remaining .arg accesses

- example/ida/graph_ir.py
- example/ida/menu.py
Modify example ida/graph_ir.py to generate ssa graph inside IDA
> add ssa graph to ida

- miasm2/expression/expression.py
> perfomance feature

- miasm2/arch/aarch64/sem.py
:warning: This PR add some float instructions, but float rounding is not handled yet. It should depend on fcpr (as in x86). This will actually result in rouding errors.
fix #906 
fix #903
> Aarch64: add mnemonic sem

- .appveyor.yml
- .travis.yml
- optional_requirements.txt
- requirements.txt
Include pip requirements.txt files and pin versions where needed
No double venv
@serpilliere this should be step 1 on #499
> cleanup travis.yml and appveyor.yml

- miasm2/arch/msp430/ira.py
- miasm2/arch/msp430/sem.py
Allow high level flags for msp430
> MSP430: Explicit flags

- .travis.yml
> parallel tests

- miasm2/arch/mep/jit.py
- miasm2/arch/x86/jit.py
- miasm2/jitter/codegen.py
- miasm2/jitter/llvmconvert.py
fix #933 
I have a though for @WilliamBruneau : don't give up #490: we will look at it together!
> Jitter: fix pc update in trace mode

- miasm2/arch/aarch64/arch.py
- miasm2/arch/aarch64/sem.py
- test/arch/aarch64/arch.py
> Updt aarch64 mn

- example/disasm/full.py
- example/ida/graph_ir.py
- example/ida/menu.py
- miasm2/analysis/data_flow.py
- miasm2/analysis/ssa.py
- test/analysis/unssa.py
- test/test_all.py
This PR implements the common first step of "Translating Out of Static Single Assignment Form" and "Revisiting Out-of-SSA Translation for Correctness, Code Quality, and Efficiency" 
This patch fixes the current Miasm UNSSA algorithm, which is buggy.
PR done with @commial. Big thanks to you man!
> SSA: fix ssa to cssa, and naive out of cssa

- example/disasm/full.py
- example/ida/depgraph.py
- miasm2/analysis/data_flow.py
- miasm2/analysis/depgraph.py
- miasm2/arch/x86/arch.py
- miasm2/arch/x86/sem.py
- miasm2/core/types.py
- miasm2/expression/expression.py
- miasm2/ir/ir.py
- miasm2/ir/symbexec.py
- miasm2/ir/symbexec_types.py
- miasm2/jitter/codegen.py
- miasm2/jitter/llvmconvert.py
- test/analysis/data_flow.py
Bad french translation:
```
Affectation -> assignment
```
> Fix bad english

- miasm2/arch/x86/arch.py
- miasm2/arch/x86/sem.py
- miasm2/core/graph.py
- test/arch/x86/arch.py
> Support for REP instruction prefix

- miasm2/core/graph.py
The function find_path_from_src does the same as function find_path, but it searches the paths from src to dst, not vice versa like find_path, which might be more efficient in multiple cases.
> Added function find_path_from_src

- miasm2/arch/x86/sem.py
> X86: fix popfw semantic

- example/disasm/full.py
- miasm2/analysis/binary.py
- miasm2/core/bin_stream.py
WARNING: base address is the negative of shift_offset
> API: replace shift_offset by base_address

- miasm2/os_dep/win_api_x86_32.py
lstrcat couldn't process unicode strings before
> lstrcat fix

- miasm2/arch/arm/arch.py
> Implement rev16 for arm

- example/disasm/full.py
- example/ida/graph_ir.py
- miasm2/analysis/data_flow.py
- miasm2/analysis/simplifier.py
- miasm2/analysis/ssa.py
- test/analysis/unssa.py
- test/ir/reduce_graph.py
Include idea and modifications described in #954
> Passes simplifier

- example/jitter/msp430.py
- miasm/jitter/JitCore.c
- miasm/jitter/JitCore.h
- miasm/jitter/Jitgcc.c
- miasm/jitter/Jitllvm.c
- miasm/jitter/arch/JitCore_aarch64.c
- miasm/jitter/arch/JitCore_aarch64.h
- miasm/jitter/arch/JitCore_arm.c
- miasm/jitter/arch/JitCore_arm.h
- miasm/jitter/arch/JitCore_mep.c
- miasm/jitter/arch/JitCore_mep.h
- miasm/jitter/arch/JitCore_mips32.c
- miasm/jitter/arch/JitCore_mips32.h
- miasm/jitter/arch/JitCore_msp430.c
- miasm/jitter/arch/JitCore_msp430.h
- miasm/jitter/arch/JitCore_ppc32.c
- miasm/jitter/arch/JitCore_ppc32.h
- miasm/jitter/arch/JitCore_x86.c
- miasm/jitter/arch/JitCore_x86.h
- miasm/jitter/bn.c
- miasm/jitter/codegen.py
- miasm/jitter/compat_py23.h
- miasm/jitter/op_semantics.c
- miasm/jitter/vm_mngr.c
- miasm/jitter/vm_mngr.h
- miasm/jitter/vm_mngr_py.c
- test/ir/ir2C.py
Remove warnings during compilation
Fix #1009
> Fix c code

- miasm/loader/elf_init.py
> Loader: fix static elf symtab

- miasm/jitter/vm_mngr.h
- setup.py
PR to fix #1038 and "ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB)" error when using the Jitter on macOS.
> Fix jitter on macOS

- miasm/jitter/loader/pe.py
This is for Python 3 compatibility
> Fix str/bytes handling in pe loader

- README.md
> doc: moved the "what" at the top

- miasm/ir/ir.py
> Remove non working/useless api from ircfg

- miasm/arch/aarch64/arch.py
- miasm/arch/aarch64/sem.py
- test/arch/aarch64/arch.py
> Aarch64: add ldarb

- miasm/arch/aarch64/sem.py
- miasm/core/asmblock.py
- test/analysis/unssa.py
- test/expression/simplifications.py
Allow complasmcfg graph completion by calling again dis_multiblock
> Updt asmblock api

- miasm/core/asmblock.py
Instruction length can change from forecast
> Asmblock: fix instruction generation

- miasm/os_dep/win_api_x86_32.py
Found these while trying to get a naive "Hello world" VS2017 binary emulating under miasm. (doesn't yet work due to string table/MBS initialization. Not yet sure if I'll chase that down.)
> win_api_x86_32: add further common windows API functions

- example/samples/x86_32_automod_2.S
- miasm/jitter/jitcore.py
- test/test_all.py
Fixed #1147
Thanks to @6oclock for the bug report!
> Fix Automod code

- README.md
It was added in the repository, but remains largely "invisible".
> Link to the IR Notebook from README

- miasm/expression/expression.py
- miasm/ir/symbexec.py
Replace french `is_aff` for `is_assign`
> Fix is_assign name

- miasm/arch/aarch64/arch.py
- miasm/arch/aarch64/sem.py
- miasm/arch/arm/arch.py
- miasm/arch/msp430/arch.py
- miasm/arch/ppc/arch.py
- miasm/arch/x86/arch.py
- miasm/arch/x86/sem.py
- miasm/core/asmblock.py
- miasm/core/cpu.py
- miasm/core/objc.py
- miasm/core/parse_asm.py
- miasm/expression/expression.py
- miasm/expression/simplifications_common.py
- miasm/ir/ir.py
- miasm/ir/translators/C.py
- miasm/jitter/codegen.py
- miasm/jitter/emulatedsymbexec.py
- test/arch/msp430/sem.py
- test/arch/x86/sem.py
Use `int(expr)` on `ExprInt` instead of `expr.arg.arg`
> Use int(expr) instead of expr.arg.arg

- miasm/jitter/vm_mngr.c
> Updt vm_read_ret_buf api

- miasm/analysis/data_flow.py
> Fix expr api updt

- example/ida/graph_ir.py
Use loc_key in ida graph_ir instead of blocks
Complement for #1185
> Fix ida graph_ir

- miasm/core/bin_stream.py
I guess it is a copy & paste error :)
> upck32be vs upck16be

- example/jitter/unpack_upx.py
Hi,
The code in `update_binary` is actually linked to the "PE rebuilding", so move it to the "PE Rebuilding" part.
Also:
* add a few comments to explain what is happening
* write the explicit code to import and use `vm2pe`
In addition, IMHO it would be simpler for people to understand and base their script on a version without the detailed PE reconstruction, but only with the `vm2pe`.
If we want to illustrate the fine grain manipulation, it could be done in another dedicated example, likely in the `loader` section.
Thoughts ?
> Rework the unpack_upx example

- miasm/arch/ppc/sem.py
> Fix ppc loc_key typo

- .travis.yml
Add loader extended tests for travis
> Add loader extended tests

- miasm/arch/arm/sem.py
- test/arch/arm/arch.py
Sorry, I have wrongly implemented the conditional code for MRC/MCR, now I have fix them.
> Wrong conditional prefix for MRC/MCR

- miasm/analysis/data_flow.py
Prevents simple FPs such as `xor eax, eax` just like in the `DependencyGraph`
> Add apply_simp to DiGraphDefUse

- miasm/os_dep/win_api_x86_32.py
- fix bug in kernel32_MultiByteToWideChar 
- implement a minimalistic kernel32_WideCharToMultiByte
> MultiByteToWideChar and WideCharToMultiByte

- miasm/os_dep/win_api_x86_32.py
When cbMultiByte = -1, the MultiByteStr input string is null-terminated.
> Fix MultiByteToWideChar when cbMultiByte = -1

- miasm/arch/x86/sem.py
> Updt x86 swap 16 bit

- example/ida/ctype_propagation.py
- example/ida/depgraph.py
- example/ida/graph_ir.py
- example/ida/symbol_exec.py
- example/ida/utils.py
- miasm/core/bin_stream_ida.py
> Ported IDAPython code to the 7.4 version

- miasm/core/types.py
- test/core/test_types.py
Hello,
Here is a fix for the issue #1255, I also added two test, let me know if it's ok
> Fix issue #1255 ; Add unit test

- miasm/arch/x86/sem.py
Fix some missing eip set for fpu instructions, see #1261
> Updt fpu set eip

- doc/locationdb/locationdb.ipynb
Add documentation for the `LocationDB` object
> Add LocationDB documentation

- miasm/ir/ir.py
Add the `IRCfgGraphviz` which generates a graphviz object, which can be used in a jupyter notebook
> Add IRCfgGraphviz class

- example/ida/ctype_propagation.py
- example/ida/depgraph.py
- example/ida/graph_ir.py
- example/ida/symbol_exec.py
Update IDA script according to `loc_db` modifications
> Fix ida examples

- miasm/arch/aarch64/arch.py
- test/arch/aarch64/arch.py
Hello,
Here is a fix for the issue : https://github.com/cea-sec/miasm/issues/1312.
Let me know what you think.
Thx,
> [AARCH64] Fix 'extr' disassembly

- example/ida/graph_ir.py
- miasm/core/modint.py
- miasm/expression/simplifications.py
- miasm/expression/simplifications_common.py
- miasm/ir/translators/z3_ir.py
- test/expression/z3_div.py
- test/test_all.py
* Fix z3 division
* Add Slice/Compose simplification
> Fix z3 div; add simpl

- miasm/arch/mep/sem.py
- miasm/arch/mips32/sem.py
- miasm/core/sembuilder.py
- test/core/sembuilder.py
As ast changes with python version, remove memX[Y] for sembuilder.
> Sembuilder: Remove mem[X]

- miasm/analysis/machine.py
jitter was initiated on both line 25 and 28
> removed duplicate assignment

- miasm/expression/simplifications.py
- miasm/expression/simplifications_common.py
- test/expression/simplifications.py
The simplification added in ce175bb51 may take reduction before
simp_cc_conds. This add simplifications for remaining case.
> Add simplification

- example/disasm/dis_binary_lift_model_call.py
- example/disasm/full.py
- test/analysis/unssa.py
> Fix ircfg_a names

- README.md
- example/jitter/mips32.py
- example/jitter/sandbox_elf_aarch64l.py
- example/jitter/sandbox_pe_x86_32.py
- example/jitter/sandbox_pe_x86_64.py
- example/jitter/test_x86_32_seh.py
- example/jitter/trace.py
- example/jitter/unpack_upx.py
- example/jitter/x86_32.py
- example/jitter/x86_64.py
- example/symbol_exec/dse_strategies.py
- miasm/analysis/sandbox.py
- miasm/jitter/jitload.py
- miasm/os_dep/linux/syscall.py
- test/arch/x86/qemu/testqemu.py
- test/arch/x86/qemu/testqemu64.py
- test/jitter/bad_block.py
- test/jitter/jit_options.py
- test/jitter/jitload.py
- test/jitter/jmp_out_mem.py
- test/os_dep/linux/test_env.py
> Replace jitter.run boolean by jitter.running

- miasm/analysis/data_flow.py
Fix memory interval generation for interference computation
> Fix interference computation

- miasm/arch/aarch64/arch.py
- miasm/arch/arm/arch.py
- miasm/arch/x86/arch.py
- miasm/core/cpu.py
Seems we can do it in one pleace in cpu.py. it simple than check value and mask in every encode() ?
> Clean encode's value check

- miasm/arch/aarch64/arch.py
- miasm/arch/arm/arch.py
- test/arch/aarch64/arch.py
- test/arch/arm/arch.py
- test/arch/mips32/arch.py
- test/arch/msp430/arch.py
- test/arch/ppc32/arch.py
- test/arch/x86/arch.py
> Fix html; Add reg test

- miasm/core/bin_stream_ida.py
- setup.py
- added a more descriptive error message to bin_steam_ida.
- fixed typo in setup.py
Please also merge: #1393
> chore: minor modifications (incl. typos)

- .gitignore
The test runs generate many files that should be ignored by git.
> chore: add generated files to gitignore file

- miasm/arch/arm/disasm.py
> fix bug of cb_arm_fix_call

- example/expression/constant_propagation.py
- example/expression/graph_dataflow.py
- example/expression/interfer.py
- example/expression/simplification_add.py
- example/expression/solve_condition_stp.py
- example/symbol_exec/depgraph.py
Few small typos / formatting in the examples
> Updates to the examples
