cea-sec/miasm

miasm2/ir/translators/python.py
I found two little bugs in TranslatorPython :
- in ``from_ExprSlice``, if the start offset is not 0, a shift operation is added to the ``out`` variable, but ``out`` was never reused.
- in ``from_ExprOp``, output could be something like : "(a + b + c & 0xffffffff)" instead of "((a + b + c) & 0xffffffff)", potentially leading to erroneous result depending on priorities of operators.
=> TranslatorPython fixes

README.md, miasm2/jitter/Jittcc.c
Take in account the #36 issue.
In order to test it, see https://github.com/serpilliere/miasm-docker/pull/3.
The README and relative comments has been updated.
=>  TCC install: use --disable-static instead of sed//-fPIC/ (see #36)

miasm2/ir/translators/__init__.py
The submodule `miasm2.ir.translators` was using wild import instead of using `import` statement to reduce the local scope footprint.
=> IR/Translators: No more usage of wild import

miasm2/arch/arm/sem.py, test/arch/arm/sem.py
Also add tests.
For extra verification I've run the secp256k1 inner field functions ( https://github.com/laanwj/secp256k1/blob/2014_12_field10x26_arm_asm/src/asm/field_10x26_arm.s - lots of `umull`/`umlal`) using `test_jit_arm`, and it produced expected outputs for my test vectors.
=> arm: Add umull,umlal,smull,smlal to sem

example/asm/simple.py, miasm2/core/asmbloc.py, miasm2/jitter/jitcore.py, test/arch/x86/sem.py
This PR applies a lint pass on `miasm2/core/asmbloc.py`. For instance, some unused arguments have been removed from the API.
In addition, the `resolve_symbol` method will no longer return a list of tuple `(BLOCK, 0)`, but a list of `BLOCK` instead (the `0` seems to be an artefact of the past).
=> Refactor asmbloc

example/ida/graph_ir.py, example/ida/symbol_exec.py, example/ida/utils.py, miasm2/expression/expression_helper.py, test/expression/expression_helper.py
This PR add a plug-in example for IDA, based on Miasm symbolic execution engine. It also features the `VarExpander` possibility.
For instance, on `samples/sc_connect_back.bin`, one selects the targeted area.
Then, by calling `symbolic_exec()` or pressing `F3`, the new view `Symbolic Execution ...` is created.
If a line is too complicated, one can expand it by pressing `E` or `Right click > Expand`.
The common code between IDA examples has been moved to `samples/ida/utils.py`.
=> Ida symbol exec

miasm2/arch/x86/sem.py
Fix the fstenv/fnstenv semantic according to intel doc: same behaviour in 32/64 bit.
=> Arch/X86: fix fsntenv in 64bit

miasm2/ir/symbexec.py
Fix int cast in symbolic execution during `ExprMem` evaluation.
=> Symbexec: fix eval_exprmem int cast

miasm2/arch/x86/sem.py
The x86/rdtsc behaviour is the same between 32/64 bit.
=> Arch/X86: fix rdtsc semantic (32/64 bit)

example/ida/graph_ir.py, example/ida/symbol_exec.py, example/ida/utils.py
In the commit 704af54e5518038eb9ab52f078dd9357ed81bf23, an `import` move was missing. Thus, the ARM support was broken.
Additionally, `Machine` is no more used in both `graph_ir.py` and `symbol_exec.py`.
=> Example/IDA: Reorganize imports

miasm2/core/bin_stream.py, miasm2/core/bin_stream_ida.py, miasm2/core/cpu.py
The `__len__` cannot be used any more in `bin_stream`: Python returns an int object, which will cap values to `0x7FFFFFFF` on 32 bit systems. A binary can have a base address higher than this, making it impossible to handle such programs.
The `__len__` is replaced by a call to `getlen`.
:warning: Elfesteem has been updated to support `max_addr` API in order to retrieve the elf/pe max virtual address. See revision `772380e060e8` on [elfesteem](https://code.google.com/p/elfesteem/source/detail?r=772380e060e856c98b65ba327ab5f7edb2a2bac4).
=> Bin stream no len

example/jitter/unpack_upx.py, miasm2/analysis/sandbox.py, miasm2/arch/arm/jit.py, miasm2/arch/x86/jit.py, miasm2/jitter/jitload.py, miasm2/os_dep/win_api_x86_32.py
This adds the possibility to call `.func_args_*()` methods with an arguments list instead of the arguments count as the parameter, and get a `collections.namedtuple`. It is still possible to use the arguments count.
The calls in `os_dep/win_api_x86_32.py` have been updated, and some bugs have been fixed there.
Thanks to @commial (kamoul0x) for your help & time.
=> Refactor API arguments

miasm2/arch/mips32/sem.py
Add docstrings in MIPS32 semantic. The goal is to help to maintain semantic, and to offer a way to retrieve the meaning of an architecture operations.
In addition, the wildcard imports of the module have been removed.
=> Comment mips32

example/ida/depgraph.py, miasm2/analysis/depgraph.py, miasm2/core/graph.py, test/analysis/depgraph.py, test/test_all.py
Introduce `DependencyGraph`, computing dependencies of elements.
The dependencies are computed through a list of blocs (`IRA`).
APIs `.get*` return an iterator on `DependencyResult`. Each one contains only relevant `DependencyNode`, which stand for an element at a given line in a given basic block. That way, **outputs contain each elements involved in the targets' value computation**.
Different outputs stand for different path through blocks (loop, if-then-else statements, ...).
In addition, the `DependencyResult` class offers some API, such as:
* a `DiGraph` output
* the symbolic execution of intermediary elements in order to get their expected value 
By defining *explicit* dependencies as dependencies only involved by instruction semantics (unlike those involved by branching), the …
=> Feature: dependency graphs

example/ida/depgraph.py, example/ida/graph_ir.py, miasm2/arch/arm/sem.py, miasm2/arch/msp430/sem.py, miasm2/arch/x86/sem.py, miasm2/expression/expression.py, miasm2/expression/expression_helper.py, miasm2/expression/simplifications_cond.py, miasm2/ir/ir.py, miasm2/ir/translators/C.py
Make expression immutable.
This may avoid bugs on the hash cache computation, and be a start point to correct hash collision.
=> Expr immutable

miasm2/jitter/Jittcc.c, miasm2/jitter/vm_mngr.c, miasm2/jitter/vm_mngr_py.c
This PR fixes 2 resources leak in the implementation of  `VmMngr` regarding `mpn` management.
It also frees pointers returned by `strdup` in `tcc_set_emul_lib_path`.
=> Resource leak in VmMngr implementation

miasm2/core/utils.py, miasm2/jitter/jitcore.py, miasm2/jitter/jitcore_tcc.py, test/core/utils.py, test/test_all.py
Introduce a new structure, called `BoundedDict`.
A bounded dict is a dictionnary limited in size.
To reduce combinatory cost, once an upper limit `max_size` is reached, `max_size - min_size` elements are suppressed.
The targeted elements are the less accessed.
One can define a callback called when an element is removed.
This structure is now used in `Jitcore` to keep the list of `label` -> `Jitted block addr`, with an arbitrary upper bound of `10000` (open to comments).
That way, the memory footprint should be reduced (as described in #29 ).
In addition, when the `Jitcore_TCC` has to delete a reference on a jitted block, the latter is freed thanks to `tcc_end` (through the deletion callback).
=> Bounded dict

miasm2/ir/ir2C.py
There is a typo in `gen_resolve_int()`.
=> ir2C: fix `gen_resolve_int()`

example/disasm/full.py, miasm2/analysis/machine.py
Export an `ir` attribute from `Machine`.
In addition, the example `disasm/full.py` uses now both `ir` and `ira`.
For instance, the following assembly lines:
```
00000000 e841414141                     call        41414146
00000005 0a                             db          0a   
```
Output (with `-g`):
```
INFO : Print blocs (without analyse)
loc_0000000000000000:0x00000000
ESP = {(ESP[0:32]+0xFFFFFFFC),0,32}
@32[(ESP[0:32]+0xFFFFFFFC)] = loc_0000000000000005:0x00000005
EIP = loc_0000000041414146:0x41414146
IRDst = loc_0000000041414146:0x41414146
INFO : Gen Graph... 0
INFO : Print blocs (with analyse)
lbl_gen_00000000:None
EAX = (loc_0000000041414146:0x41414146 call_func_ret ESP)
ESP = (loc_0000000041414146:0x41414146 call_func_stack ESP)
IRDst = loc_0000000000000005:0x00000005 …
```
=> Machine ir

miasm2/analysis/depgraph.py
This PR ensures that element returned by `DependencyGraph.get*` are always copies of internal elements.
In addition, the heads of the `ira` graph are also used as bound for the algorithm (like user-specified `heads`).
Indeed, with a graph which looks like:
```
+---------+         +---------+
| 1)      |         | 2)      |
|         |         |         |
|  HEAD   |         |         |
|         |         |         |
|         |         |         |
+----+----+         +------+--+
|                     |   
|                     |   
|                     |   
|     +---------+     |   
+-----> 3)      +-----+   
|         |         
|         |         
|         |         
|         |         
+----+----+         
|              
+----v----+         
| 4)      |         
| Tracked | …
```
=> Fix depgraph

miasm2/core/bin_stream_ida.py
This PR fixes the behavior of `getlen` when several segments are present.
=> BinStreamIDA: `getlen` is now lazy, and use the proper IDA API

miasm2/jitter/vm_mngr_py.c
There was a NULL deref in `vm_set_mem_access`.
The value returned by `get_memory_page_from_address` is checked everytime but not in this function. Others check:
* vm_mngr.c:169
* vm_mngr.c:220
* vm_mngr.c:257
* vm_mngr_py.c:276
* vm_mngr_py.c:205
Before the PR:
```Python
sb.jitter.vm.set_mem_access(0x1555, 2)
WARNING: address 0x1555 is not mapped in virtual memory:
Segmentation fault (core dumped)
```
After:
```Python
sb.jitter.vm.set_mem_access(0x1550, 2)
WARNING: address 0x1550 is not mapped in virtual memory:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: cannot find address
```
=> VmMngrPY: Null Deref in `set_mem_access`

example/ida/depgraph.py, example/ida/graph_ir.py
Replace mentions to `/tmp/` by `tempfile.gettempdir()` to be more platform-independent (thks to Joel Eriksson <je@clevcode.org>).
=> Example/IDA: Replace /tmp/ by tempfile.gettempdir (credits @OwariDa)

miasm2/ir/translators/z3_ir.py
This PR makes TranslatorZ3 actually use its cache. I "just" forgot to put values in it in the previous PR...
=> TranslatorZ3: now uses its cache (forgotten lines...)

miasm2/analysis/depgraph.py
Ridiculously increase `DepGraph` performance.
In some corner cases, the complexity go from factorial to polynomial. Indeed, irrelevant path were conserved and used during comparison. That is to say, to be equal, two depnodes must have visited the same basic blocks with same elements. It's a good thing when one of these element is relevant (ie. is a `modifier`), but not when none of them are relevant.
In addition, some pure data-structures improvement have been done.
An naive hash on `DepDict` has not been used because there are a lot of collisions. Indexing `DepDict` by `label` seems to be a more efficient patch.
=> Faster depgraph

README.md
The current TCC version is in development, and committed versions aren't stable.
The Dockerfile has been updated accordingly (https://github.com/serpilliere/miasm-docker/pull/4).
=> README: TCC *stable* version should be use

README.md
It seems that most of reversers use the Windows version of IDA, particularly for available plugins.
This PR add some quick steps to describe how to have a part of Miasm (actually, everything except the jitter part) working on Windows through IDA.
These steps have been tested with an IDA 6.6 on a Windows 7, with the following plugins:
* `symbol_exec.py`
* `graph_ir.py` (if nodes are blank, just wait a few seconds for the IDA refresh)
* `depgraph.py`
=> README: add a workaround for Windows & IDA

miasm2/analysis/depgraph.py, test/analysis/depgraph.py
Fix a bug in the generation or the `irbloc`.
When extracting lines of expressions present in the relevant nodes, we can have duplicated lines.
This generated twice emulation of the same expressions.
Add single step support in symbolic execution for easier debugging of `depgraph` emulation.
=> Fix depgraph emul

miasm2/core/cpu.py, test/arch/x86/arch.py
The `b` attribute of an instruction represents its binary encoding.
The prefix was missing in this representation.
This fixes the issue #95.
A regression test is added.
=> Fix x86 prefix bin

miasm2/jitter/jitload.py
Allow using `Machine` even if `VmMngr` is not installed (Ex: IDA)
=> Jitter: vmmngr may not be present (for example in IDA python)

example/disasm/full.py, miasm2/analysis/binary.py, miasm2/jitter/loader/elf.py, miasm2/jitter/loader/pe.py, test/test_all.py
With this PR, container loaders know how to extract architecture information from container (ELF, PE).
`Container` objects have now an attribute `arch` to get this information.
For instance:
```Python
Container.from_stream(open("samples/box_upx.exe")).arch
```
The `disasm/full.py` example has been modified to use this information when no architecture is specified.
In addition, the `address` argument can now be empty, to reach the code which use the `entry_point` instead.
A regression test has been add to check this case.
The architecture guessing has been tested on busyboxs and Miasm samples.
=> Container arch

.travis.yml
Add the `.travis.yml` configuration file according to the current `DockerFile`.
This configuration file is used by the [Travis CI](https://travis-ci.org/) service.
=> TravisCI: Configuration file for the Travis continuous integration framework

miasm2/analysis/depgraph.py
Remove non necessary `ira` creation
=> degraph: remove useless ira creation

example/ida/depgraph.py, miasm2/analysis/depgraph.py, test/analysis/depgraph.py
Support callback to filter depnode to follow.
Update IDA/Depgraph to support `NoCallNoMem` depgraph.
=> Depgraph filter

miasm2/expression/simplifications_common.py, test/expression/simplifications.py
Fix simplification for multiplication:
Fix needed for issur #128 
```
elif (isinstance(e.arg, ExprOp) and
e.arg.op == "*" and
isinstance(e.arg.args[-1], ExprInt)):
args = [e_s.expr_simp_wrapper(a[e.start:e.stop]) for a in e.arg.args]
e = ExprOp(e.arg.op, *args)
```
The comment is correct, but the code doesn't do what's in the comment. The code which checks the slice begins with a 0 (in the [0:y]) is not present.
=> Fix mul simp

miasm2/ir/ir2C.py, miasm2/ir/translators/C.py, miasm2/ir/translators/miasm.py, miasm2/ir/translators/python.py, miasm2/ir/translators/translator.py, miasm2/ir/translators/z3_ir.py, test/ir/ir2C.py, test/ir/translators/z3_ir.py
With this PR, translators are now used with instance.
That way, a cache (here bounded thanks to `BoundedDict`) can be used on expression and shared accros translators.
In addition, some translators (ie. `z3`) need to share attributes during recursion calls (`Z3_mem`). This way is less hacky than the previous one.
Thanks to @fmonjalet for the idea.
=> Cache translators

miasm2/arch/x86/sem.py
pxor doesn't change any flags, so I'm not sure if this is needed:
```
e += update_flag_logic(c)
e.append(m2_expr.ExprAff(a, c))
```
=> added semantics for x86 pxor

miasm2/ir/translators/z3_ir.py
fixes this:
```
/usr/lib/python2.7/site-packages/miasm2/ir/translators/z3_ir.pyc in from_ExprOp(cls, expr)
170                     res = res << arg
171                 else:
--> 172                     raise NotImplementedError("Unsupported OP yet: %s" % expr.op)
173         elif expr.op == 'parity':
174             arg = z3.Extract(7, 0, res)
NotImplementedError: Unsupported OP yet: idiv
```
=> added translation for idiv command in z3

miasm2/analysis/binary.py, miasm2/analysis/gdbserver.py, miasm2/arch/arm/arch.py, miasm2/arch/msp430/arch.py, miasm2/arch/sh4/arch.py, miasm2/arch/x86/arch.py, miasm2/core/asmbloc.py, miasm2/core/cpu.py, miasm2/jitter/jitload.py, miasm2/jitter/loader/elf.py, miasm2/jitter/loader/pe.py, miasm2/jitter/loader/utils.py, miasm2/os_dep/win_api_x86_32.py, miasm2/os_dep/win_api_x86_32_seh.py
In Python, the pattern:
```Python
log.info("my %s format %x string" % ("little", 4))
```
Can be re-written (avoiding an unnecessary pre-computing of format string):
```Python
log.info("my %s format %x string", "little", 4)
```
See [PyLint logging-not-lazy](http://docs.pylint.org/features.html) and [PEP 0282](https://www.python.org/dev/peps/pep-0282/) for more information.
=> Remove lazy logging pattern

miasm2/analysis/sandbox.py
This is needed at least to "implement" `GetModuleHandle`.
=> Sandbox Win: add PE object to win_api_x86_32.winobjs

miasm2/arch/x86/jit.py
=> x86/StdCall: Fix a typo when 2 values are returned (credits niko schmidt)

test/test_all.py, test/utils/testset.py
Add an option `--do-not-clean` in `test_all.py` to avoid cleaning tests products (use case: debugging sessions).
=> Test "do not suppr" option

miasm2/expression/expression.py, test/expression/expression.py, test/test_all.py
The expressions are compared using only hash, which is prone to collisions.
The PR keeps the use of the hash, but equality is done on the expression's representation. This is a bit weird but it seems there are no obvious solutions to this problem, including singleton pattern.
=> Fix expr hash

miasm2/arch/mips32/sem.py, miasm2/core/sembuilder.py, test/core/sembuilder.py, test/test_all.py
Add a helper to make instruction semantic writing easier and more readable.
For instance:
```Python
@sb.parse
def mov(a, b):
a = b
mem32[a] = mem32[b]
```
Will be translated to:
```Python
def mov(ir, instr, a, b):
return [ExprAff(a, b), ExprAff(ExprMem(a, 32), ExprMem(b, 32))], []
```
A part of the *Mips32* semantic has been rewritten accordingly.
=> Printable sem

miasm2/jitter/arch/JitCore_arm.c, miasm2/jitter/arch/JitCore_mips32.c, miasm2/jitter/arch/JitCore_msp430.c, miasm2/jitter/arch/JitCore_x86.c
On 32 bit systems, the high bytes of `size` are not set to 0 to generate random argument to be send to `automod_cb`, so generate a random behaviour in regression tests.
Fix every architectures.
=> Jitter: fix cast for 32 bits machines

example/symbol_exec/depgraph.py, miasm2/analysis/depgraph.py, test/test_all.py
Finalize the PR #148. Add a binding with z3 to retrieve constraints on solutions paths and try to solve them.
For instance, giving `samples/simple_test.c`:
```
$ python symbol_exec/depgraph.py samples/simple_test.bin -i --rename-args -m x86_32 0x0 0x8B eax
Solution 0: EAX: 0x1005 -> sol_0.dot
Satisfiability: True {arg0: '0x7', EBP_init: '0x88'}
Solution 1: EAX: 0x1005 -> sol_1.dot
Satisfiability: False 
Solution 2: EAX: 0x1001 -> sol_2.dot
Satisfiability: True {arg0: '0x0', EBP_init: '0x88'}
Solution 3: EAX: 0x1007 -> sol_3.dot
Satisfiability: False 
Solution 4: EAX: 0x1007 -> sol_4.dot
Satisfiability: True {arg0: '0x42', EBP_init: '0x88'}
Solution 5: EAX: 0x1008 -> sol_5.dot
Satisfiability: False 
Solution 6: EAX: 0x1008 -> sol_6.dot
Satisfiability: True {EBP_init: '0x88', arg0: …
```
=> Depgraph z3

miasm2/core/graph.py
`roots` has been forgtotten in PR #153
=> Graph: replace forgotten root api

test/test_all.py, test/utils/testset.py
Fix the `--coverage` option of `test_all.py`.
For information, with the current test set, I obtain:
statements | missing | excluded | coverage
----|---|---|---
29330 | 8509 | 0 | 71%
=> TestAll: Coverage mode was broken

README.md
Add a link to http://miasmdoc.ajax.re (see #162).
=> Add a link to the auto-generated documentation

example/disasm/file.py, test/test_all.py
Since 9ee9492606c62cfc3ae8dc50aa6ac0bf09b0d45b, the address used for `box_upx.exe` was wrong.
=> TestAll: Update disasm 'file.py' example address

miasm2/expression/simplifications_common.py
Those statements are already enforced by simplifications' way-of-calling
=> Simplifications: Remove useless statements

miasm2/__init__.py, miasm2/analysis/__init__.py, miasm2/arch/__init__.py, miasm2/core/__init__.py, miasm2/expression/__init__.py, miasm2/ir/__init__.py, miasm2/jitter/__init__.py, miasm2/os_dep/__init__.py
This PR adds a quick hint on modules behavior.
* `miasm2`: Reverse engineering framework in Python
* `miasm2.analysis`: High-level tools for binary analysis
* `miasm2.arch`: Architectures implementation
* `miasm2.core`: Miasm's core elements
* `miasm2.expression`: Intermediate language implementation
* `miasm2.ir`: Intermediate reprensentation methods
* `miasm2.jitter`: JIT feature
* `miasm2.os_dep`: Operating System dependent methods
May you have better definitions ?
=> Inits: Add docstring for main modules

miasm2/core/asmbloc.py, miasm2/core/cpu.py
Hi,
This PR aims at improving error handling in two cases:
* When calling `symbol_pool.set_offset(None, offset)` (this could be extended to catch all cases where the first argument has no 'name' attribute), a more meaningful exception is raised.
* When assembling a block containing undefined labels (labels whose offsets are still equal to `None` when assembling). The previous behavior was to silently replace the labels offset with 0, which seems to be, in most cases, bug-prone. It now raises an exception (and it does not break the tests!).
Cheers,
Florent
=> Symbol pool error handling

example/disasm/full.py
`followcall` option was not used.
=> Example/Disasm/Full: fix follow_call option

miasm2/arch/x86/arch.py
`LDS`, `LES`, ... have the same reg addressing constraint as `LEA`
=> x86: avoid load effective reg

miasm2/analysis/depgraph.py, test/analysis/depgraph.py, test/test_all.py
The DependencyNodes are now all distincts, in order to handle dependency loops properly.
(cf test graph 13). The DependencyNode step attribute represent the moment the node was encountered.
The emulation part of DependencyResult will emulate the value along the path
represented by the DependencyGraph (loops included).
=> Dependency graph

README.md
elfesteem from google code doesn't work any longer with the new aarch64 support. So, I updated the README.md with the contents of the travis file.
=> README: fixed elfesteem documentation

miasm2/expression/expression.py, miasm2/ir/analysis.py
:warning: API change: `is_func_call` is now linked to an `ExprOp` instead of an `ExprAff`
`Depgraph.py` is not changed because it *already* relies on this new behaviour.
=> Expression: move is_func_call to expr scr

miasm2/analysis/sandbox.py
Allow stack base modification without rewriting whole class. Many code is duplicated, here: maybe a solution will be found in the future to factorize arch classes.
=> Sandbox: add stack base manipulation

test/test_all.py
This is a simple orthograph fix, but in a parameter name, so we better do it before it spreads too much in other scripts.
=> Orthograph fix in parameter: rename --ommit-tags to --omit-tags.

example/jitter/unpack_upx.py, miasm2/analysis/debugging.py, miasm2/analysis/gdbserver.py
With this PR, `unpack_upx` with GDBServer will properly finish the binary rebuilt (instead of crashing on `sb.run`) on connexion closing (client side).
In addition, if one set a script breakpoint thanks to `sb.add_breakpoint` which doesn't return `True` - ie execution should stop - a sig TRAP is raised and script execution can continue after connexion closing.
That way, one can easily set a breakpoint to get back control on GDBserver client when getting the OEP in UPX.
=> Fix gdbserver

miasm2/core/asmbloc.py
Thanks to @commial & @p-l-
Enhance dot style for basicbloc graph.
=> Core/asmbloc: Fix dot generation for basic blocs

miasm2/core/utils.py, miasm2/jitter/jitload.py
Hi,
This PR speeds up some of the python code used by the jitter:
- `BoundedDict`'s `Counter` is replaced with a simple `dict` {key -> int}. This makes the run loop twice as fast on programs where compilation time is way inferior to the jitted code execution time (typically programs with intensive loops).
- in `runiter_once`, a preliminary check is made before checking all the callbacks. This brings something like 20% speedup.
Globally, most of the time is wasted by the huge function call overhead of python. As discussed previously with @serpilliere, moving the whole `continue_run`, or at least `runiter_once` loop in C would grant a great speedup (an additional x5 or x10 seems pretty reachable).
Profiling have mainly been performed with cProfile and Runsnakerun.
Here is how it looked like …
=> Optimize jitter execution time

miasm2/core/utils.py, miasm2/ir/ir2C.py, miasm2/jitter/JitCore.h, miasm2/jitter/Jittcc.c, miasm2/jitter/jitcore.py, miasm2/jitter/jitcore_python.py, miasm2/jitter/jitcore_tcc.py, miasm2/jitter/jitload.py
This PR modifies the way `jittcc_exec_bloc` work: now, the next block to be executed is fetched during the C loop when it's possible (no exception has been raised, no breakpoint to handle, the block is already jitted).
That way, in many case (such as *inlined strlen*), there is no need to go back and forth between Python and execution, leading to a faster execution.
On my tests, it cut execution time by 3 to 5 (on 10 min examples).
=> Feature cloop

example/disasm/file.py, example/disasm/full.py, example/jitter/mips32.py, example/jitter/msp430.py, example/symbol_exec/depgraph.py, miasm2/analysis/debugging.py, miasm2/analysis/sandbox.py
Use Python's int(s, 0) to allow string "s" to specify its base where
addresses and offsets can be supplied.
This change makes the situation homogeneous among the various examples and
interactive usage.
=> In interactive use, allow C-like prefixes to choose the base of integers

example/jitter/unpack_upx.py
This PR try to enhance the skeleton of the example `unpack_upx.py`.
For instance, a mention to `vm2pe` API has been added, the `GetProcAddress` hook has been commented, ...
=> Fix unpackupx

example/disasm/callback.py, miasm2/arch/aarch64/disasm.py, miasm2/arch/arm/disasm.py, miasm2/arch/x86/disasm.py, miasm2/core/asmbloc.py, test/test_all.py
With this PR, disasm callback are called with named arguments, avoiding declaring callback with:
```Python
def callback(mn, attrib, pool_bin, cur_bloc, offsets_to_dis, symbol_pool)
```
But only with required arguments:
```Python
def callback(cur_bloc, mn, *args, **kwargs):
```
=> Keyword disasm cb

miasm2/arch/x86/sem.py
The current equation of the x86 `aflag` is way too complicated. Update for more homogeneity (`popfd`, `popfw`, `sahf`, ...)
=> x86/sem: unify the way aflag is computed (like popfd/w, sahf)

miasm2/arch/x86/sem.py
Update `tsc2` value (`tsc1:tsc2` from `rdtsc`) on `tsc1` overflow
=> x86/Sem/RDTSC: update tsc2 value on tsc1 overflow

example/symbol_exec/single_instr.py
Rewrite `example/symbexec/single_instr.py` in order to be more comprehensible / to use more common Miasm APIs.
=> Fix symbexec example

miasm2/arch/x86/sem.py, miasm2/ir/translators/C.py, miasm2/jitter/vm_mngr.c, miasm2/jitter/vm_mngr.h
This PR aims to enhance the x86 float support, by adding new instructions, fixing some of them and a better approximation of a few instruction behaviour.
For a better emulation, a soft float library should be used (current operations are done on 64bits representations).
In addition, the Python jitter (and then the expression simplification engine) should be enhanced accordingly.
=> Fix float x86

miasm2/arch/x86/sem.py, miasm2/expression/simplifications_common.py, miasm2/ir/translators/C.py, miasm2/jitter/vm_mngr.c, miasm2/jitter/vm_mngr.h, test/expression/simplifications.py
This PR aims to fix the semantic of some x86 instructions, and corresponding TCC implementations (like #265 ).
Special note for `SHRD`, `SHLD`: the implemtation takes care of "unspecified state" according to the result obtained on my host, and on QEMU.
=> Fix sem x86

miasm2/expression/modint.py, miasm2/expression/simplifications_common.py, test/expression/simplifications.py
Fix `idiv` and `imod` constant propagation computing.
Add `>>>c_rez` and `>>>c_rez` constant propagation calculation.
=> Fix python emul

miasm2/arch/x86/sem.py, test/test_all.py
Fix the semantic of BCD instructions in x86, according to QEMU ( see #274 ).
The behavior used in AAA/AAS comes from this [errata](http://www.hugi.scene.org/online/coding/hugi%2017%20-%20coaax.htm).
=> Fix x86 bcd

miasm2/arch/x86/sem.py, test/test_all.py
Adds `iret[d]` to x86 semantic, and enables QEMU `test_misc` test (see #274 ).
In addition, a tag `qemu` has been added to QEMU regression tests, in order to be quickly ignored when running a quick `test_all.py`.
On a testing host:
* Avoiding `long`: 3m40s
* Avoiding `long,qemu`: 42s
=> Fix x86 misc

test/analysis/depgraph.py
Since b8b0e21a, `test/analysis/depgraph.py` has been leaved unchecked by regression test framework.
=> Test/Depgraph: the error status was not checked

example/disasm/full.py, example/expression/asm_to_ir.py, example/expression/get_read_write.py, example/expression/graph_dataflow.py, example/ida/depgraph.py, example/ida/graph_ir.py, example/symbol_exec/depgraph.py, miasm2/analysis/data_analysis.py, miasm2/analysis/depgraph.py, miasm2/arch/x86/ira.py, miasm2/ir/analysis.py, miasm2/ir/ir.py, test/analysis/depgraph.py, test/ir/analysis.py, test/test_all.py
This PR refactors the relation between IR and IRA.
The code which is always trustable (which does not depend on the current ABI, etc. such as `dead_simp`) has been transfered from IRA to IR.
In addition, IRA is no more an old-style object, but inherits from IR. That way, the presence of `self.blocs`, for instance, is ensured.
Finally, the associated graph (was `self.g`, now `self.graph`) is now lazy computed. The call to `gen_graph` is no more needed, avoiding some algorithm per-requisites (DependencyGraph, dead simp).
:warning: the API `.graph()` does not longer return the DOT text of the graph, but the `DiGraphIR` instance associated. DOT can be obtain thanks to `.graph.dot()`.
=> Refactor ira

miasm2/expression/smt2_helper.py, miasm2/ir/translators/smt2.py, test/ir/translators/smt2.py, test/test_all.py
This PR introduces a translator for the SMT2 standard. With this, SMT formulas can be solved independently from Z3 by any SMT solver that supports the standard.
=> SMT2 translator

miasm2/core/asmbloc.py, miasm2/core/bin_stream.py, miasm2/core/bin_stream_ida.py, miasm2/core/cpu.py
This PR aims to speed-up the disassembly engine, by targeting its interaction with `BinStream` objects.
Now, a call to `bin_stream.getbits` always produce one call to `bin_stream.getbytes` (instead of `ceil(number of bits asked / 8)` calls).
In addition, there is a new mode named *Atomic Mode*. When the `BinStream` is in this mode, accesses may be cached.
Typically, when disassembling one instruction, one wants to work on a read-only memory (ie. without concurrent accesses). So, during this process, the `BinStream` enters in the atomic mode, avoiding the fetch of each instruction bit by re-parsing and checking internal structures in Elfesteem.
On my test, that is to say the disassembly of a 4000 basic blocks function, the speed gain is x2.
=> Speedup disasm

miasm2/arch/mips32/arch.py, miasm2/core/asmbloc.py, miasm2/core/parse_asm.py
With this PR:
* `asm_constraint` always takes a `label` at init, and this `label` must be an  `asm_label` instance
* block list of ASM returned during disassembling / assembling have this property: for a given block and a given destination:
* there is only one constraint between these two blocks (starting from the first block)
* if, during construction, there are several constraint with the same type, pick one of them
* if, during construction, there are several type of constraint with at least one `c_bad`, raise an error
* if, during construction, there are both `c_next` and `c_to`, conserve only `c_to`
For instance:
```
JNZ next
next:
....
```
now returns only one constraint `c_next` for the `JNZ` block (in order to simplify algorithms).
In addition, a fix on delayslot management in …
=> Refactor asmlabel

miasm2/arch/aarch64/arch.py, miasm2/arch/arm/arch.py, miasm2/arch/mips32/arch.py, miasm2/arch/msp430/arch.py, miasm2/arch/sh4/arch.py, miasm2/arch/x86/arch.py, miasm2/core/cpu.py, miasm2/expression/expression.py, miasm2/expression/expression_helper.py
Uses `__slots__` in `Expression` and in `Instruction` classes to limit memory usage.
=> Instruction slots

miasm2/core/asmbloc.py, miasm2/jitter/jitcore.py
With this PR, an error during disassembling is no more represented with a specific constraint `c_bad` (that is to say an edge in basic blocks graph using `.bto` as in `bbl2graph`), but thanks to an extension of `asm_bloc`named `asm_block_bad`.
Indeed, this information seems to be more related to the basic block than links between them.
That way, constraints between blocks are conserved, and are always `c_to` or `c_next`.
In addition, a specific error number (or a specific *stringable* object) can be attached to the `asm_block_bad` to clarify the reason of the error.
So, for instance, printing block of `example/disasm/full.py example/samples/box_upx.exe` outs:
```
...
loc_00000000004076B1:0x004076b1
MOV        DWORD PTR [EBX], EAX
ADD        EBX, 0x4
JMP …
```
=> Feature asmblockbad

miasm2/core/asmbloc.py, miasm2/core/graph.py, test/core/graph.py
Introduce `MatchGraph`, which aims to be the counterpart of `MatchExpr` for graphs.
It is composed of `MatchGraphJoker`, which are joker for nodes, giving custom restrictions.
From the corresponding docstring:
```
If j1, j2 and j3 are MatchGraphJoker, one can quickly build a matcher for
the pattern:
|
+----v----+
|  (j1)   |
+----+----+
|
+----v----+
|  (j2)   |<---+
+----+--+-+    |
|  +------+
+----v----+
|  (j3)   |
+----+----+
|
v
Using:
>>> matcher = j1 >> j2 >> j3
>>> matcher += j2 >> j2
Or:
>>> matcher = j1 >> j2 >> j2 >> j3
```
Then, one can iterate over solutions using `matcher.match(graph)`, an iterator on dictionnary *joker ->matched graph node*.
Restrictions can be applied on jokers, for instance:
* `restrict_in`: if not set, the corresponding node can have more predecessors …
=> Feature MatchGraph

miasm2/ir/symbexec.py, miasm2/jitter/emulatedsymbexec.py, miasm2/jitter/jitcore_python.py, miasm2/jitter/jitload.py, test/ir/symbexec.py, test/jitter/jitload.py, test/test_all.py
This PR introduces `jitter.eval_expr`, a way to eval Miasm IR expression in the execution context, and related tests. Side effects of the expression are taken into account (ie in case of `ExprAff`).
The redundant code snippets with the core of `miasm2.jitter.jitcore_python` have been moved in a new class `EmulatedSymbExec`.
For instance:
```Python
jitter.eval_expr(ExprId("RAX")) == jitter.cpu.RAX
jitter.eval_expr(ExprAff("RAX", ExprInt64(14)) == ExprInt64(14)
jitter.cpu.RAX == 14
```
For other example, see `test/jitter/jitload.py`.
=> Eval_Expr in jitter context

example/expression/get_read_write.py, miasm2/analysis/data_analysis.py, miasm2/analysis/depgraph.py, miasm2/arch/aarch64/ira.py, miasm2/arch/aarch64/sem.py, miasm2/arch/arm/ira.py, miasm2/arch/mips32/ira.py, miasm2/arch/msp430/ira.py, miasm2/arch/x86/ira.py, miasm2/arch/x86/sem.py, miasm2/expression/expression.py, miasm2/ir/analysis.py, miasm2/ir/ir.py, miasm2/ir/ir2C.py, miasm2/ir/symbexec.py, test/analysis/depgraph.py, test/core/sembuilder.py, test/ir/analysis.py
This PR introduces the new `AssignBlock` object representing (and replacing) parallel `ExprAff`.
IR parallels side effects were represented using a list of `ExprAff`. The list has no point here, as the affectations are not ordered. `AssignBlock` is a dictionnary based object. Its keys are the affected objects, the values are their equations.
:warning:  This PR breaks some API, but code modification should be minimal.
Work realized with @commial: Big thanks!
=> Assignblock

miasm2/core/asmbloc.py
Avoid a break after each *block merging* simplification, because during the algorithm we know which blocks we have to ignore to avoid conflicting simplification.
That way, a `graph.copy()` (a very costly operation) is only done after a full pass, and not after each simplification, resulting in a very perceptive speed up of the pass.
=> Speed up block merging

miasm2/core/asmbloc.py
This prevents an error message when splitting a block at its end address.
=> Fix range checking when splitting blocks

miasm2/expression/expression_helper.py, test/expression/expression.py
Introduce `possible_values`, which outs the possible values of an `Expr` associated with its constraints.
For instance:
```Python
possible_values(
Expr...
)
(0x2+0x3) with constraints:
<cond2 != 0>
<cond1 == 0>
(0x2+0x4) with constraints:
<cond1 == 0>
<cond2 == 0>
(0x1+0x4) with constraints:
<cond1 != 0>
<cond2 == 0>
(0x1+0x3) with constraints:
<cond1 != 0>
<cond2 != 0>
```
Thanks to @serpilliere
=> Expr possible

example/disasm/full.py, miasm2/analysis/binary.py, test/test_all.py
Introduce `Container.symbol_pool`, a `asm_symbol_pool` instance with detected symbols.
To use it, one should use:
```Python
with open(...) as fdesc:
cont = Container.from_stream(fdesc)
mdis = disasm_engine(cont.bin_stream, symbol_pool=cont.symbol_pool)
```
This behavior has been added to `disasm/full.py` example:
```
$ python disasm/full.py ../test/arch/x86/qemu/test-i386 test_lea
...
INFO : func ok 000000000804b8f0 (0)
...
```
`graph_execflow.dot`:
Fix #338
=> Introduce Container.symbol_pool, containing container symbols (if any)

miasm2/core/asmbloc.py, miasm2/jitter/jitcore.py
Handle #344 point 1 .
This PR moves `dis_bloc` and `dis_bloc_all` from public to protected domain, inside the `disasmEngine` class.
In addition, the jitter is now using the `disasmEngine` for reaching new block.
Finally, the docstring of `disasmEngine` and its methods have been completed.
=> Refactor disasm engine

miasm2/core/types.py, test/core/test_types.py
This PR fixes some API incoherences in `miasm2.core.types (more to be fixed later :) ):
* `Array` constructor can now take either a `Type` instance or a `MemType` subclass (like `Ptr` do).
* `Ptr.dst_type` is now a `Type` and not a `MemType`. Beware of this last change, as it is not API compatible.
=> Fix miasm2.core.types API

miasm2/arch/x86/sem.py
x86 sem: Fixed missing size in idiv
=> x86 sem: Fixed missing size in idiv

miasm2/ir/ir2C.py, miasm2/jitter/JitCore.c, miasm2/jitter/JitCore.h, miasm2/jitter/jitcore_gcc.py, miasm2/jitter/jitcore_tcc.py, miasm2/jitter/vm_mngr.c, miasm2/jitter/vm_mngr.h
This PR adds block caching for the  gcc/tcc `jitter`. Running a binary more than once will speedup the execution time **greatly**.
=> Jitter cache block

miasm2/jitter/Jitgcc.c, miasm2/jitter/Jittcc.c
Fix bad function casting in [gcc/tcc] jitter.
Fix issue #371
=> Jitter: fix function cast

miasm2/jitter/vm_mngr.c
Without this PR, Sibyl grows up to a 16GB RAM use in less than 20 secs on my tests.
With this PR, the amount of RAM used is rather stable
=> Fix a memory leak in reset memory page pool

miasm2/core/bin_stream.py
Elfesteem may raise a `ValueError` while getting bytes (for instance, in elfesteem/elf_init.py, line 624, in get_rvaitem: `raise ValueError('unknown rva address! %x' % start)`) . Miasm disassembly engine handle read issues through `IOError`.
=> Handle Elfesteem ValueError on 'get'

miasm2/ir/translators/z3_ir.py
Implicit boolean comparisons broken by recent commit a2eb824 in Z3Prover/z3 causing translator to break.
Callstack of failure.
/usr/local/lib/python2.7/dist-packages/miasm2/ir/translators/z3_ir.pyc in from_ExprCompose(self, expr)
142             sube = self.from_expr(subexpr)
143             e = z3.Extract(stop-start-1, 0, sube)
--> 144             if res:
145                 res = z3.Concat(e, res)
146             else:
/usr/lib/python2.7/dist-packages/z3.py in __nonzero__(self)
294
295     def __nonzero__(self):
--> 296         return self.__bool__()
297
298     def __bool__(self):
/usr/lib/python2.7/dist-packages/z3.py in __bool__(self)
304            return self.arg(0).eq(self.arg(1))
305         else:
--> 306             raise Z3Exception("Symbolic expressions cannot be cast to …
=> Explicitly compare z3 expression to None.

.travis.yml, README.md
Update z3 location, to avoid recurring problems with codeplex download and to follow the right repository.
The version is forced in order to avoid API problems (but using the latest version should probably work).
(Inspired from #392 )
=> Update z3 requirement

miasm2/jitter/vm_mngr.c
I think it's better to call find_page_node() with the right range (min to max) rather than "fixing" the max.
=> Fix get_memory_page_from_address()

miasm2/arch/arm/sem.py
Add support to convert all the `smul[tb][tb]` and `smulw[tb]` variants into expressions.
=> arm: Add sem support for smul and smulw instructions

miasm2/core/asmbloc.py
With this patch, we can tell miasm which functions are non-returning so that disassembly stops after a call to such a function.
Joint work with @carolineLe
=> add dont_dis_retcall_funcs set to disasmEngine

miasm2/ir/symbexec.py, test/ir/symbexec.py
Add a way to insert "a knowledge" in a symbol execution context.
If the current context is:
```
a = 0
```
Then, on `b = a`:
* `apply_expr`, `eval_ir` will end with (applying the side effect of an instruction):
```
a = 0
b = 0
```
* `apply_change` will end with (injecting a statement):
```
a = 0
b = a
```
In the last example, the value of `b` is the initial value of `a` (`_init` are no longer needed since #445)
=> Regression test for apply_expr/apply_change/eval_ir

miasm2/jitter/codegen.py
Remove a few redundancy in `codegen`.
In addition, a corner case is "watched" through an assert, the details are in the commit comment.
If this case is trigger one day, one will hopefully just have to blame this assert to find the concern about it.
I prefer this way instead of fixing now the bug, because no example raising it comes to my mind with current M2 implemented architectures.
=> Remove useless code

miasm2/core/cpu.py
This message is more helpful when debugging a new architecture disassembler.
=> Raise with a more helpful message on multiple disassemblies

.travis.yml, README.md, miasm2/ir/translators/C.py, miasm2/jitter/Jitllvm.c, miasm2/jitter/arch/JitCore_x86.c, miasm2/jitter/jitcore_llvm.py, miasm2/jitter/llvmconvert.py, miasm2/jitter/vm_mngr.c, miasm2/jitter/vm_mngr.h, test/test_all.py
As stated in #5, the current support of LLVM is broken.
In this work, the Numba [llvmlite](https://github.com/numba/llvmlite) backend is used instead of pyllvm.
One of its main advantage is that the IR module is entirely built in Python, and the LLVM backend is only called at the end (avoiding wasting time in the wrapper, as before). In addition, it is more up to date.
As a lot of internal API have changed since the first use of LLVM (`IRDst`, `vm_MEM*`, breakpoints, code generation optimisations as `codegen`, JiT loop while code is already Jitted with an optional maximum number of iteration, `VmMngr` move to `JitCpu` attribute, specific `dump_gpregs` for certain architecture, ...), the current code base needs a big update (perhaps a merge with `codegen`).
Here is a TODO list of what is …
=> Feature llvm jitter

miasm2/ir/ir.py
Use block API `get_next` to determine linked block.
If no block is linked in the IR graph, use default behavior (next offset)
=> IR: fix set_empty_dst using c_next

test/test_all.py, test/utils/testset.py
Add the possibility to launch tests regarding only a subset of tag (whitelist version of `omit-tags`).
For instance:
```
$ python test_all.py -o z3
...
Result: 27/27 pass
```
This is quite useful while, for instance, refactoring a given Miasm segment...
=> Add a only-tags option for test_all

miasm2/arch/aarch64/regs.py
The WZR register is defined three times.
Before the patch:
```
>>> from miasm2.arch.aarch64.regs import all_regs_ids
>>> len(all_regs_ids), len(set(all_regs_ids))
(234, 232)
```
After the patch:
```
>>> from miasm2.arch.aarch64.regs import all_regs_ids
>>> len(all_regs_ids), len(set(all_regs_ids))
>>> (232, 232)
```
=> Duplicated WZR definition

miasm2/arch/aarch64/ira.py, miasm2/arch/arm/ira.py, miasm2/arch/mips32/ira.py, miasm2/arch/msp430/ira.py, miasm2/arch/x86/ira.py, miasm2/ir/analysis.py
Since #469, call effects are placed "inline" in IR blocks.
This PR applied this *wanted* behavior for all architectures (ie. by default), except for mips32 due to delayslot issues
=> Let x86 'pre_add_instr' be the default behavior

miasm2/arch/x86/arch.py, miasm2/arch/x86/sem.py, miasm2/expression/expression.py, miasm2/jitter/emulatedsymbexec.py, miasm2/jitter/llvmconvert.py
Memory access pointers size are fixed in IR and arch dependent.
On x86:
16bit: 32
32bit: 32
64bit: 64
Arm: 32
aarch64: 64
Mips32: 32
...
Reason:
* Before patch, write to `@32(ExprInt(10, 16))` won't respond to a read to `@32(ExprInt(10, 32))`
* the size of `segm` operator is fixed for a given arch
:warning: API change:
`is_op_segm`: [MODIFIED] returns True if is `ExprOp` and `op == 'segm'`
`is_mem_segm`: [ADDED] returns True if is `ExprMem` and ptr `is_op_segm`
=> Fix mem accesses

example/expression/solve_condition_stp.py, miasm2/arch/aarch64/arch.py, miasm2/arch/arm/arch.py, miasm2/arch/mips32/arch.py, miasm2/arch/msp430/arch.py, miasm2/arch/sh4/arch.py, miasm2/arch/x86/arch.py, miasm2/core/cpu.py, miasm2/core/parse_asm.py, test/arch/aarch64/unit/asm_test.py, test/arch/mips32/unit/asm_test.py, test/arch/x86/arch.py, test/arch/x86/unit/asm_test.py
Determine label/integer sizes using context
Default size in other cases
Use '_' in assembly to reference address next to current instruction
=> Fix asm parsing

.travis.yml, README.md, example/expression/access_c.py, example/expression/expr_c.py, example/samples/human.S, miasm2/arch/x86/ctype.py, miasm2/core/ctypesmngr.py, miasm2/core/objc.py, test/test_all.py
This module implements C basic manipulators.
From C types descriptions, we can now give back C code representing a Miasm expression.
For exemple on the struct:
```C
struct human {
unsigned short age;
unsigned int height;
char name[50];
};
struct ll_human {
struct ll_human* next;
struct human human;
};
```
If we know that RSI is `ptr` and `ptr` is a `struct ll_human*`
we can say that:
`@32[(@64[@64[ptr]]+0xC)]`
has type `uint`
and can be acessed in C with:
```C
((((ptr)->next)->next)->human).height
```
See `example/expression/access_c.py` executed on  `human.bin`
=> Objc feature

miasm2/jitter/codegen.py, test/jitter/test_post_instr.py, test/test_all.py
PC must not be reevaluated on post instruction error.
(llvm backend not affected)
Bug raised and corrected with @commial 
Thanks @commial !
=> Jitter: fix post instr exception

miasm2/arch/mips32/jit.py, miasm2/jitter/codegen.py, miasm2/jitter/jitcore_cc_base.py, miasm2/jitter/jitcore_llvm.py, miasm2/jitter/llvmconvert.py
Support different symbool names in identical jitter block
:warning: the `log_mn` keeps displaying old symbols
=> Jitter: fix symb cache name

miasm2/os_dep/win_api_x86_32.py
This mimics the behaviour of kernel32_GetProcAddress()
=> set breakpoint handler in ntdll_LdrGetProcedureAddress()

example/disasm/full.py, example/expression/simplification_add.py, example/expression/simplification_tools.py, example/expression/solve_condition_stp.py, example/jitter/sandbox_elf_aarch64l.py, example/jitter/sandbox_pe_x86_32.py, example/jitter/sandbox_pe_x86_64.py, example/jitter/unpack_upx.py, example/jitter/x86_32.py, test/arch/aarch64/arch.py, test/arch/arm/arch.py, test/arch/mips32/arch.py, test/arch/msp430/arch.py, test/arch/sh4/arch.py, test/arch/x86/arch.py
Remove 'PYTHONSTARTUP' auto-completion trick in example and tests:
* this is related to the environment of the user, not to Miasm
* it brings unnecessary imports
* it had complexity to example for no reasons
=> Remove PYTHONSTARTUP in end-user scripts

miasm2/jitter/arch/JitCore_aarch64.c, miasm2/jitter/arch/JitCore_arm.c, miasm2/jitter/arch/JitCore_mips32.c, miasm2/jitter/arch/JitCore_msp430.c, miasm2/jitter/arch/JitCore_x86.c, miasm2/jitter/vm_mngr_py.c
Don't return 1337 on void python wrappers
Add input sanity checks on python wrappers
=> Jitter: sanitize code

miasm2/jitter/JitCore.h, miasm2/jitter/arch/JitCore_x86.c
Raise error if setting a jitter register with something else than an integer (or long)
=> Jitter: Error on reg set not int

miasm2/expression/expression.py
A classic error in Miasm is to confuse ExprInt with int, for example:
ExprId('a') + 3
We could return ExprOp('+', ExprId('a') + ExprInt(3, 32)), but this
may (and often) mask a problem in the source, so we forbid such a
construction (and assert this to clarify the error)
=> Expression: Forbid mix between Expr and int/long

miasm2/jitter/vm_mngr_py.c
A typo in e1c0d1f03a6e245cb5cbceac72231f1317cc4173 had replace a `RuntimeError` by a `TypeError` when an address is not found on `vm.get_mem`, leaving a misleading error.
=> Raise a RuntimeError (as before) when addr is not found

miasm2/analysis/dse.py
If there was any, the callback may be called after the execution of
several instruction, instead of the expected one-by-one
=> Ensure there is no multi-line basic block in the cache

example/disasm/callback.py, example/ida/ctype_propagation.py, miasm2/analysis/dse.py, miasm2/core/asmblock.py, miasm2/jitter/jitcore.py, test/core/asmblock.py
WARNING: disasmEngine behaviour modification
Before patch: job_done containted the already disassembled addresses. If the
user disassembled twice the same addresse, the engine will return empty
object on the second call.
After patch: If the user disassemble twice the same addresse, the engine will
return result of the disassembling in both cases.
=> Asmblock: remove disasm engine job_done attribute

miasm2/core/cpu.py
Fix missing relase on _atomic_mode that leads to a crash if getbits fails because no content is available
=> fix atomic_mode leak

example/ida/ctype_propagation.py
Display the destination type if it's a memory variable, and we know its
type (we consider source and destination have the same type).
=> Example/ctype: fix propagation on mem write

miasm2/core/graph.py, test/core/graph.py
just noticed that the returned back edge wasn't a back edge :D
=> DiGraph: fixed node order in natural loop backedges

miasm2/os_dep/common.py, miasm2/os_dep/linux_stdlib.py, miasm2/os_dep/win_api_x86_32.py, test/os_dep/common.py, test/os_dep/linux/stdlib.py, test/os_dep/win_api_x86_32.py, test/test_all.py
This PR contains various Win32 API additions/fixes:
* add a get_size method to Miasm heap object, which allows the
implementation of mscvrt_realloc
* add the concept of "current directory", with the default value being
arbitrary set to "c:\tmp", which allows the implementation of
{Get,Set}CurrentDirecrtory
Various other methods implemented:
- advapi32_RegCloseKey
- advapi32_RegCreateKeyW
- advapi32_RegSetValueExA
- advapi32_RegSetValueExW
- kernel32_GetProcessHeap
- msvcrt_delete
- msvcrt_fprintf
- msvcrt_fwrite
- msvcrt__mbscpy
- msvcrt_new
- msvcrt_realloc
- msvcrt_sprintf
- msvcrt_srand
- msvcrt_strrchr
- msvcrt_swprintf
- msvcrt_wcscat
- msvcrt_wcscmp
- msvcrt_wcscpy
- msvcrt__wcsicmp
- msvcrt_wcslen
- msvcrt_wcsncpy
- msvcrt__wcsnicmp
- msvcrt_wcsrchr
=> Various Win32 API additions/fixes

.travis.yml, miasm2/jitter/llvmconvert.py
Fix #630 
LLVMlite globals management has changed (`KeyError` instead of returning `False` on miss).
This PR:
* Update the corresponding API calls
* Switch to pip LLVMlite version in Travis CI to follow the README
* Use `trusty` distrib to obtain the required LLVM-4.0 toolchain
=> Fix/support llvmlite 0.20

.travis.yml
LLVMLite is now in version 0.21, and requires LLVM-5.0.
Should fix #642 regression test error
=> Travis: switch to llvm-5.0 for LLVMLite 0.21

miasm2/jitter/arch/JitCore_arm.c, miasm2/jitter/vm_mngr.c
Avoid unwanted behavior when `i` reach too high value (`1` being signed, `1 << 32` ends up with a `0xffffffff....` value, breaking the expected mask comparison.
=> Fix BSR / BSL / CLZ implementation to avoid signed overflow

miasm2/arch/x86/arch.py, miasm2/arch/x86/sem.py, test/arch/x86/arch.py
This PR fixes and introduces new SSE instructions for x86.
These instructions have been tested with LLVM jitter against QEMU `test-i386`, function `test_sse`. The XMM (with 128 bits) patch is necessary to reproduce these tests.
Without the patch, the first 12 lines of the tests works.
With the patch, the first 224 lines are now working (next instruction to be implemented being `SHUFPS`).
=> Add SSE instructions

miasm2/ir/translators/z3_ir.py
Avoid importing a pretty big module, and the side effects of z3, such as
declaring the stack as unlimited
=> Translator: import 'z3' only when it is really needed

miasm2/expression/simplifications_common.py, test/expression/simplifications.py
This PR fixes 3 bugs obtained by fuzzing Miasm simplifications against z3.
With this PR, my fuzzer is not able to find any more  bugs after ~ 4 000 000 tries (with `ExprRandom`, expression size of depth 8, expr_reuse set to `True`, `ExprMem` of the same size in a given expression).
=> Fix a few simplifications

miasm2/jitter/loader/elf.py
If given by the ELF file, use its endianness to set the PLT entries
accordingly.
=> Enforce correct endianness of PLT entries

miasm2/arch/ppc/arch.py
The 011111 group of store instructions is split in two sets: one in
which r0 has value 0, and another where r0 mustn't be used.
A "typographical inversion" interverted the two sets, leading to
a semantics error when r0 is used with the subset which expects a
hardcoded 0 value.
Found by @commial, thanks!
=> Fix the 011111 group of store instructions wrt r0

miasm2/arch/aarch64/sem.py
Hi, 
I have added the  code for parsing ARM register extender instructions, viz. sxtb, sxth, sxtx, uxtw, uxth, uxtx, uxtb. I have tested it for UXTW, and assumed the things will be same for other instructions as well. 
For reference, apart from ARM ASM documentation, I have used this blog https://community.arm.com/processors/b/blog/posts/a64-shift-and-extend-operations-operand-modifiers. 
Please let me know if anything is missing.
=> Added support to parse  sxtb, sxth, sxtx, uxtw, uxth, uxtx, uxtb

miasm2/jitter/vm_mngr.h
Hi,
This diff permits to use miasm on OpenBSD.
Cheers,
Sigalpes.
=> Fix build on OpenBSD

example/ida/ctype_propagation.py, example/ida/depgraph.py, example/ida/graph_ir.py, example/ida/symbol_exec.py, example/ida/utils.py, miasm2/analysis/binary.py, miasm2/expression/expression_reduce.py, miasm2/ir/symbexec.py
Some arch like ARM depends on address in order to determine which
attributes have to be used during analysis
=> Example/ida: use addr to guess arch

miasm2/arch/mips32/arch.py
Here is a small PR that I encounter while playing with the following small binary:
```
J          0x4
NOP
```
=> Fix mips32 dstflow2label()

miasm2/arch/x86/arch.py, miasm2/arch/x86/sem.py, miasm2/expression/expression.py, miasm2/ir/translators/C.py, miasm2/jitter/arch/JitCore_x86.h, miasm2/jitter/llvmconvert.py, miasm2/jitter/op_semantics.c, miasm2/jitter/op_semantics.h, test/arch/x86/arch.py, test/test_all.py
This PR introduces new, and merge old, float operations and Miasm representation (based on IEEE-754).
Basically, a float is always stored as a bitcast in its corresponding size. To perform floating point operation in jitters, it is first convert (bitcasted) to a floating point in the corresponding jitter abstraction, the operation is computed, and it is save again as a bitfield. In others words, corresponding ExprOp are atomic in the sense that they expect a packed (value's bits) value in input, and also out a packed value.
Operations are regrouped in this way:
- fpconvert_fp32, fpconvert_fp64, fpconvert_fp80: convert from a floating point to another (truncate or extend)
- sint_to_fp32, sint_to_fp64, sint_to_fp80: convert from a signed integer to a floating point number (original size can …
=> Better float support & additionnal SSE

miasm2/arch/arm/jit.py
Arguments were not pushed correctly on the stack (for functions with
more than four arguments)
=> Fix ARM C function calling

miasm2/arch/mep/sem.py
Here is a small fixes, that allows to use Sibyl.
=> Incorrect ir_mepb.addrsize definition

miasm2/analysis/dse.py
When the symb_concrete execution is needed, EmulationSymbExec is
used. In the previous version, it was writing in Memory. If the current
instruction is reading and writing at the same place, the jitter
instance may have a different behavior than the symb concrete one
=> DSE: fix a bug happening in rare case

miasm2/jitter/JitCore.h, miasm2/jitter/arch/JitCore_x86.c
References on PyLong where lost.
Memory exhaustion may hapen in python jitter because of high usage of
get/set register.
=> Jitter: Fix memory leak

miasm2/arch/aarch64/sem.py, miasm2/arch/arm/sem.py
A minor bug fix, in ARM and Aarch64, in the respective exceptions of MRS and MSR, instruction names have been interchanged. Fixed it in the PR.
=> In ARM & Aarch64 MSR and MRS instructions' exception wrong names used

miasm2/arch/x86/sem.py, miasm2/ir/translators/C.py
When an operation of type shift / rotate is translated a temporary basic block is generated to handle 0-rotate / 0-shift.
Thus when working in 64-bit mode with a 32-bit operand, the result will never be zero-extended to 64-bit.
E.g:
```py
from miasm2.arch.x86.arch import mn_x86
from miasm2.core import asmblock, parse_asm
from miasm2.arch.x86.ira import ir_a_x86_64
from miasm2.ir.symbexec import SymbolicExecutionEngine
from miasm2.expression.expression import ExprInt
asmcfg, loc_db = parse_asm.parse_txt(mn_x86, 64, '''
main:
MOV        RAX, 0x00
MOV        RCX, RAX
MOV        RAX, 0x4142434445464748
MOV        RDX, RAX
ROR        EDX, CL
RET
''')
asmblock.asm_resolve_final(mn_x86, asmcfg, loc_db)
ir_arch = ir_a_x86_64(loc_db)
ircfg = ir_arch.new_ircfg_from_asmcfg(asmcfg)
symb = …
```
=> X86 sem : mov assignexpr rot / shift

miasm2/expression/simplifications.py, miasm2/expression/simplifications_common.py, test/expression/simplifications.py
Best effort to simplify simple add/multiply operators:
```
a + a*3 => a*4
a*2 + a << 2 => a*6
...
```
This is useful as compilators often replace expensive multiplications by shift/add operations.
=> Simple: add multiplication simplification

miasm2/jitter/op_semantics.c, miasm2/jitter/op_semantics.h
Hello,
I encountered a problem when jitting the following code with GCC:
```
MOV     RCX, 0x3401281234
MOV     RDX, 0x12345678
BSR     RDX, RCX
```
`RDX` is equal to `0x0000000100000025` instead of `0x0000000000000025`.
When looking at the generated `C` file here is line where the problem occurs (as the function `cntleadzeros` return type is `unsigned int`, cf https://github.com/cea-sec/miasm/blob/master/miasm2/jitter/op_semantics.h#L40):
```C
var_64_00 = (((((-(cntleadzeros(0x40, mycpu->RCX)))&0xffffffffffffffff) + 0x3fULL)&0xffffffffffffffff))&0xffffffffffffffffULL;
// ^ bad cast here :(
```
```python
from elfesteem.strpatchwork import StrPatchwork
from miasm2.arch.x86.arch import mn_x86
from miasm2.core import asmblock, parse_asm
from miasm2.arch.x86.ira import ir_a_x86_64
from …
```
=> change return type of cntleadzeros to uint64_t

miasm2/arch/x86/sem.py, miasm2/ir/translators/C.py, miasm2/jitter/codegen.py
Hello,
You are gonna hate me but there is still some problems...
My test case was not good enough because the same bug is still present when using the GCC JIT.
I didn't catch the issue because when the IR was displayed, the assignation was as follow:
`RDX = zeroExt_64(RDX[0:32])`
But in fact the operation returned was:
`ExprAssign(ExprId('EDX', 32), ExprId('EDX', 32))`
So under the python jitter, the zeroextend was done, but not under GCC JIT, the operation disappeared in the generated C file.
Now the fix create the following asssignation expression:
`ExprAssign(ExprId('RDX', 64), ExprOp('zeroExt_32', ExprId('EDX', 32)))`
Now the test seems ok with python or GCC JIT.
Sorry for the inconvenience.
=> Revert 879 mov assignexpr rot shift ; Simplify assignexpr rot shift & patch simplification

miasm2/arch/x86/sem.py
Hello,
When an operation of type CMOV is translated a temporary basic block is generated, thus when working in 64-bit mode with a 32-bit operand, the result will never be zero-extended to 64-bit.
This is a clone of some previus pull request but for CMOV instruction.
Test case:
```python
from elfesteem.strpatchwork import StrPatchwork
from miasm2.arch.x86.arch import mn_x86
from miasm2.core import asmblock, parse_asm
from miasm2.arch.x86.ira import ir_a_x86_64
from miasm2.ir.symbexec import SymbolicExecutionEngine
from miasm2.expression.expression import ExprInt
def get_bytes(patches):
output = StrPatchwork()
for offset, raw in patches.items():
output[offset] = raw
return str(output)
def print_ir(loc_db, asmcfg):
ir_arch = ir_a_x86_64(loc_db)
ircfg = ir_arch.new_ircfg_from_asmcfg(asmcfg) …
```
=> X86 SEM CMOV : add zeroextent if destination size is 32

miasm2/arch/x86/sem.py
Hello,
In the function `_shift_tpl`, the count (`c`) parameter is used without beeing masked for overflow condition & carry flag filling.
I encountered the following case where the result was not the expected one, with `A=0x1234FDB512345678`, `B=0x21AD96F921AD3D34`, `C=0x21` as entry in `SHLD A[0:32], B[0:32], C`  and the output is equal to `0x00000000435a7a68` instead of `0x000000002468acf0`.
Test case:
```python
from elfesteem.strpatchwork import StrPatchwork
from miasm2.arch.x86.arch import mn_x86
from miasm2.core import asmblock, parse_asm
from miasm2.arch.x86.ira import ir_a_x86_64
from miasm2.ir.symbexec import SymbolicExecutionEngine
from miasm2.expression.expression import ExprInt
def get_bytes(patches):
output = StrPatchwork()
for offset, raw in patches.items():
output[offset] = …
```
=> X86 SEM SH[LR]D : use masked count for all expression in _shift_tpl

miasm2/arch/mep/sem.py, test/arch/mep/ir/test_branchjump.py
While jitting a MeP binary with gcc, it discovered that the BGEI instruction semantic is not correct. Here is the fix.
=> Correct MeP BGEI semantic

miasm2/expression/expression.py
The optional `dct` is pointless here. At worst, it's an empty dictionary.
=> Expr: fix replace_expr args

miasm2/arch/aarch64/sem.py
warnings: as other instructions, the carry flag (result of shifted arg?) is not computed.
=> Aarch64: fix bics

setup.py
On many platforms, the `python` binary links to python 3. This change makes the setup script use python2 explicitly
=> Make python version explicit

miasm2/os_dep/win_32_structs.py
A little typo in the ContextException structure.
ContectFlags replaced by ContextFlags, as described by Microsoft https://docs.microsoft.com/fr-fr/windows/desktop/api/winnt/ns-winnt-_wow64_context
=> fix: typo in ContextException structure

miasm2/arch/x86/arch.py
Instruction prefix wasn't shown when to_string method was used since instruction_x86(https://github.com/cea-sec/miasm/blob/master/miasm2/arch/x86/arch.py#L452) used just the inherited one from instruction(https://github.com/cea-sec/miasm/blob/master/miasm2/core/cpu.py#L997) which doesn't support these prefixes. It is used perhaps by AsmBlock(https://github.com/cea-sec/miasm/blob/master/miasm2/core/asmblock.py#L147) and it makes the prefixes invisible for it and many others.
=> Not shown instruction prefix

miasm2/jitter/vm_mngr_py.c
Remove warning we had at build time
=> VmMngrPy: remove unused 'size' var

miasm2/jitter/jitcore.py, miasm2/jitter/jitcore_python.py, miasm2/jitter/llvmconvert.py
Fix #936 
This PR rewrites the python jitter internal to better match what have been done for CC & LLVM based jitter. For instance:
* delayslot handling
* exception with and without PC update, with or without registers update
* moment of call of logging utils
* avoid to return to jitload too often
=> Rewrite Python jitter

miasm2/ir/translators/z3_ir.py
As stated in
https://github.com/Z3Prover/z3/blob/master/src/api/python/z3/z3.py
"Use the operator <= for signed less than or equal to."
=> Translator/z3: fix tipo in z3 cmp operators

example/disasm/full.py, miasm2/analysis/data_flow.py, miasm2/analysis/outofssa.py, miasm2/analysis/ssa.py, test/analysis/unssa.py
When doing IR simplifications, `IRDst` can be simplified from an `ExprCond` to a simple  `ExprLoc` for example in obfuscated codes. The `ircfg` may then be updated to reflect the lost of an edge.
Until now, this job couldn't be done as some passes (like unssa) takes a sanitized `ircfg` in ssa form, meaning each `phi` source can be tracked back to it's assignments... which is not the case if we simply delete edges during graph simplifications.
This patch add the `Phi` update after edges deletion. This gives more interesting IR simplifications. 
Example here with the following input `ircfg`:
which gives (after ssa form transformation and simplifications):
This PR resolves the first question of #954 by @KosBeg
Note: regression tests will be added after the factorization and "librarization" …
=> Del unused dst in ir simp

miasm2/core/bin_stream_ida.py
API change from shift_offset to base_address,  broke bin_stream_ida.py. Fixing the issue in this PR.
=> Fix for bin_stream_ida after change in shift_offset API

miasm/expression/simplifications_common.py
if len(left) is more than 1, it will occur 'tuple' object has no attribute 'op'
=> 'tuple' object has no attribute 'op'

miasm/expression/simplifications.py, miasm/expression/simplifications_common.py, test/expression/simplifications.py
First version of a simplification pass to simplify expressions like `ExprOp('&', ExprCompose(...), mask)`. This is the kind of output expected:
```
>>> from miasm.expression.simplifications import expr_simp
>>> from miasm.expression.expression import *
>>> expr_simp(ExprCompose(ExprInt(0, 24), ExprId('a', 8) & ExprInt(0xFF, 32))
0x0
```
=> Add compose_and_mask simplification pass

.travis.yml
see: https://travis-ci.community/t/cannot-apt-get-install-clang-5-0/3250
=> Travis: switch from trusty to xenial

miasm/os_dep/win_api_x86_32.py
Hello,
I'm not really sure about this one, but `kernel32_WriteFile` seems to write bytearrays. So in case of a `GENERIC_WRITE`, the file should be open in `wb` mode.
It should correct the error:
```
[INFO]: kernel32_CreateFile(lpfilename=0x13fdd1, access=0x40000000, dwsharedmode=0x0, lpsecurityattr=0x0, dwcreationdisposition=0x2, dwflagsandattr=0x80, htemplatefile=0x0) ret addr: 0x40212b
[INFO]: kernel32_WriteFile(hwnd=0x259, lpbuffer=0x40307c, nnumberofbytestowrite=0x7600, lpnumberofbyteswrite=0x40305c, lpoverlapped=0x0) ret addr: 0x40214c
Traceback (most recent call last):
File "sandbox.py", line 15, in <module>
sb.run()
File "/usr/local/lib/python3.6/dist-packages/miasm/analysis/sandbox.py", line 524, in run
super(Sandbox_Win_x86_32, self).run(addr)
File …
```
=> modify CreateFile to open file in binary-mode

miasm/arch/x86/arch.py, miasm/arch/x86/sem.py
This change adds support for [`roundss`](https://www.felixcloutier.com/x86/roundss) and [`roundsd`](https://www.felixcloutier.com/x86/roundsd) instruction.
Three new ops are added for rounding:
- 'fpround_towardsnearest': rounds to nearest int, even for ties
- 'fpround_down': rounds to nearest int <= float
- 'fpround_up': rounds to nearest int >= float
- 'fpround_towardszero'(existing): rounds to nearest int s.t. |int| <=
|float|
For a variant of roundsd that uses mxcsr register as the rounding mode,
currently we assume it's fpround_towardsnearest. This may cause trouble
if the program modifies MXCSR register.
Fix #1069
=> Add roundss/roundsd

miasm/os_dep/win_api_x86_32.py
It seems that a python import was missing here :
```
$ python sandbox_pe_x86_64.py ./something.dll_.bin
[WARNING]: Create dummy entry for 'kernel32.dll'
[WARNING]: Create dummy entry for 'user32.dll'
[WARNING]: Create dummy entry for 'secur32.dll'
[WARNING]: Create dummy entry for 'msvcrt.dll'
[INFO]: msvcrt_memset(addr=0x13ff78, c=0x0, size=0x18) ret addr: 0x140001e10L
Traceback (most recent call last):
File "sandbox_pe_x86_64.py", line 15, in <module>
sb.run()
File "/usr/local/lib/python2.7/dist-packages/miasm/analysis/sandbox.py", line 560, in run
super(Sandbox_Win_x86_64, self).run(addr)
File "/usr/local/lib/python2.7/dist-packages/miasm/analysis/sandbox.py", line 135, in run
self.jitter.continue_run()
File "/usr/local/lib/python2.7/dist-packages/miasm/jitter/jitload.py", line 405, in …
```
=> Adds a missing import

example/jitter/unpack_upx.py, example/symbol_exec/dse_crackme.py, miasm/analysis/depgraph.py, miasm/analysis/dse.py, miasm/analysis/sandbox.py, miasm/core/utils.py, miasm/jitter/jitload.py, miasm/jitter/loader/elf.py, miasm/jitter/loader/pe.py, miasm/jitter/loader/utils.py, miasm/os_dep/common.py, miasm/os_dep/linux/syscall.py, miasm/os_dep/linux_stdlib.py, miasm/os_dep/win_api_x86_32.py, miasm/os_dep/win_api_x86_32_seh.py, test/arch/x86/qemu/testqemu.py, test/arch/x86/qemu/testqemu64.py, test/os_dep/linux/stdlib.py, test/os_dep/win_api_x86_32.py, test/test_all.py
Clean `get_str_*` API
`get_str_ansi` decoded strings using utf8 and was blindly used for pure
windows function (`LoadLibraryA`) and for `stdlib` functions (printf,
strlen, ...) even if strlen does not use utf8...
New API is:
`get_win_str_a`/`get_win_str_w` and `set_win_str_a`/`set_win_str_w` for
windows (respectively `codepage1252`/`windows utf16`) .Those functions
should only be used in windows strings manipulations, so there are taken
out of the jitter.
`get_c_str`/`set_c_str`: as those functions are "classic" in OSes, they are
keeped in the jitter.
The z3 fix is there to cover Attribute error in z3 import for some distribs.
=> Path are str

miasm/core/sembuilder.py
Python3.8 changes the signature of ast.Module by adding a
ignore_comment field which breaks this project. ast.parse("")
is a dirty but more compatible way to make it work in both
Python 3.8 and <3.8.
Fixed #1092
=> sembuilder: more compatible way to construct AST module

miasm/arch/x86/sem.py
Only REPE and REPNE exist at the binary level, but Miasm allows "REP" when
assembling x86 instructions. Make the semantics aware of this instead
of ignoring the REP prefix.
The bug could not occur when disassembling a binary program.
=> Fix semantics of REP prefix.

miasm/jitter/llvmconvert.py
The caching of memory read was missing. This speeds up llvm jitter from multiple point of view:
- llvm can optimze code as no more side effects interfer with code
- avoid calling mem read multiple times
Here is the generated llvm IR for `inc byte ptr [eax]` before (note the multiple `mem_lookup_08`):
```
loc_key_3:
%".22" = bitcast [36 x i8]* @"printf_format_1" to i8*
%".23" = call i32 (i8*, ...) @"printf"(i8* %".22")
%"RAX" = load i64, i64* %".15"
%".24" = and i64 %"RAX", 4294967295
%".25" = trunc i64 %".24" to i32
%".26" = zext i32 %".25" to i64
%".27" = call i8 @"MEM_LOOKUP_08"(i8* %"jitcpu", i64 %".26")
%".28" = zext i32 %".25" to i64
%".29" = call i8 @"MEM_LOOKUP_08"(i8* %"jitcpu", i64 %".28")
%".30" = sub i8 0, 1
%".31" = sub i8 0, %".30"
%".32" = add i8 %".29", %".31"
%".33" = icmp …
```
=> Jitter/llvm: Fix llvm Memory lookup cache

miasm/os_dep/win_api_x86_32.py
Id(xxx) is actually used to generated handles on windows os_dep A future
patch will add handles generation / management for windows environement.
=> Win_API: Temporary fix for ids in 64 bits

miasm/analysis/dse.py
=> DSE: on mem_read, use parent behavior instead of no treatment

miasm/os_dep/linux/environment.py
According to ``man 2 mmap``: 
> The mapping is not backed by any file; its contents are initialized to zero.  The fd argument is ignored; however, some implementations require fd to
be  -1  if  MAP_ANONYMOUS  (or MAP_ANON) is specified, and portable applications should ensure this.  The offset argument should be zero.  [...]
Offset parameter is ignored if MAP_ANONYMOUS is set.
=> mmap: ignore offset if MAP_ANONYMOUS set

miasm/arch/x86/jit.py
In Microsoft Windows 64bit, the `stdcall` calling convention allocates some space on the stack, called shadow space, corresponding to the parameters given in registers (cf [https://en.wikipedia.org/wiki/X86_calling_conventions](https://en.wikipedia.org/wiki/X86_calling_conventions#List_of_x86_calling_conventions)).
This means that, at the entry point of a function taking more than 4 parameters, the fifth parameter is at `RSP + 0x8 + (0x8 * 4)`.
=> Fix bug in Microsoft x86-64 calling convention

miasm/arch/x86/jit.py, miasm/os_dep/linux/environment.py, miasm/os_dep/linux/syscall.py
This PR aims to provide the minimalist environment for `x86_32` ELF binaries on Linux (based on what was done for `x86_64`. In particular:
* add a class `LinuxEnvironment_x86_32` (empty for now),
* implement calling convention for syscalls on Linux 32bit in the jitter,
* add a syscall table for `x86_32`,
* implement `syscall_x86_32_newuname` (actually copy from `x86_64`).
=> Linux x86_32: minimalist environment and syscall table

miasm/ir/symbexec.py
I've noticed that reading even single `Expr` from memory triggers `ExprCompose`.
For example when one writes `ExprId("R8_init")` into a memory address and subsequently reads it, I'd expect `ExprId("R8_init")` to be also returned. However the result is `"{R8_init 0 64}"`, repeating these actions creates `"{{R8_init 0 64} 0 64}"`, `"{{{R8_init 0 64} 0 64} 0 64}"`...
It doesn't seem to be intended behaviour to me, are there any legitimate reasons for it?
=> MemSparse potential read issue

miasm/analysis/data_flow.py, miasm/analysis/depgraph.py, miasm/analysis/dse.py, miasm/expression/expression.py, miasm/expression/simplifications.py, miasm/expression/simplifications_common.py, test/expression/expression.py
**Expression visit order**
In the current Expression visitor, some implementations errors
result in usage limits.
First, the default behavior. Let analyse the following code:
```python
from miasm.expression.expression import *
a = ExprId('a', 32)
b = ExprId('b', 32)
c = ExprId('c', 32)
j1 = ExprId('j1', 32)
j2 = ExprId('j2', 32)
d = a + b
e = d * a
print("expr: %s" % e)
result = e.replace_expr({d:j1, a: j2})
print("result: %s" % result)
```
which gives:
```
expr: (a + b) * a
result: (j2 + b) * j2
```
We can ask ourselves why we didn't reduce first:
```(a*b) -> j1```
instead of
```a -> j2```
(which eliminates the possibility of the first reduction rule)
The general question is:
- When visiting an expression, must we apply reductions rules from top to bottom
or bottom to top?
- must we …
=> Add Expression visitor

miasm/analysis/dse.py
Hello,
It seems there is a type error that happens only in Python3 when using the DSE.
Basically, when a lib handler is added for the DSE, the following code is executed if the function was not implemented.
https://github.com/cea-sec/miasm/blob/9f052f39ca4c72c1b6146d445f7764c57876013a/miasm/analysis/dse.py#L261
In Python3, this code raises a Type Error as `libimp.fad2cname[dse.jitter.pc]` is a `str` and not a bytes-like object.
I think this issue can be solved by adding a call to `force_bytes`.
=> Type Error when using the DSE with Python3

miasm/core/asmblock.py
If one deletes all the direct predecessors of a pending block, it dosn't get freed even thought it's not required anymore. Since all the pendings are recalculated here, there's no reason not to cover these cases here IMHO by clearing them prior the recalculation. Another solution is to add a watcher to del_block().
=> Minor improvement in rebuild_edges

.appveyor.yml, miasm/jitter/jitcore_cc_base.py, miasm/jitter/jitcore_gcc.py, miasm/jitter/jitcore_llvm.py, optional_requirements.txt, setup.py
On Windows with Python38 the Jitter fails to compile mostly because of the native extension filenames `.cp38-win_amd64.lib`.
Therefore:
- during setup, some libs are misplaced
- bad extension in `jitcore_cc_base.py` (`sysconfig.get_config_var('EXT_SUFFIX')` is `.pyd` but we need `.lib` here)
- use hardcoded `python27.lib`
=> Fix jitter on Windows

miasm/arch/ppc/sem.py
Two expression in PPC sem.py using ExprInt() do not have size and raise "__new()__ missing 1 required positional argument: 'size'"
=> Fix ExprInt() without size in PPC

miasm/arch/mips32/sem.py, miasm/arch/ppc/sem.py
"ins" MIPS opcode and PPC byte_swap() use the old API for ExprCompose() which produces a "TypeError: unhashable type: 'list'" exception. I have convert them to use the new API.
=> Fix bug 'ins' MIPS opcode and PPC "byte_swap()"

miasm/arch/mips32/arch.py, miasm/arch/mips32/sem.py, test/arch/mips32/arch.py
I have introduced the following working opcodes:
LH BNEL BEQL BLEZL BGTZL BC1TL BC1FL BLTZL
with the exception of LH, which loads an halfword, the other opcodes are the "likely" version of existing branch instructions: if the branch is not taken they do not execute the delay slot instruction.
I have introduced also these opcodes but I have implemented them with "nop" because I'm not so confident with IR expressions:
SWL SWR CFC1 CFT1
=> Add new MIPS opcodes

miasm/arch/ppc/sem.py
PPC mn_do_lmw() and mn_do_stmw() raise exception because try to extract the source/destination address using int() from an ExprMem object.
=> Fix mn_do_lmw() and mn_do_stmw()

miasm/os_dep/win_api_x86_32_seh.py
In the Loader linked list initialization, the blink of the first entry was NULL in the following lists:
InMemoryOrderLinks
InInitializationOrderLinks
InLoadOrderModuleList
This PR fixes the blink to point to the real last entry of the linked list.
=> Fix win ldr first entry's blink

example/disasm/full.py, miasm/analysis/data_flow.py, miasm/analysis/simplifier.py
This PR replaces the code responsible of "Expression propagation" used to simplify and deobfuscate code. The new code uses propagation of equivalence classes through basic blocks  in order to reveal possible simplifications.
For example:
```
B = A+1
C = A
A = 6
D = [B]
```
Will result in:
```
B = A+1
C = A
A = 6
D = [C+1]
```
To deal with pointer aliases, the code uses a "may interfer" which can be customized (sub classed) by the user.
This code is quicker, simpler, more correct than the actual `ExprPropagation`.
=> Updt propagation expression algorithm

miasm/os_dep/win_api_x86_32.py
According to the documentation, if cchWideChar is 0, then
the required size for the buffer indicated by lpWideCharStr
is returned.
=> Win_api: fix kernel32_MultiByteToWideChar

miasm/expression/simplifications_common.py
Input `expr` such as `(ESP_init + 0xFFFFFFA8) == (ESP_init + @32[ESP_init + 0xFFFFFECC] * 0x2 + 0xFFFFFFA8)` resulted in empty `args_a` which caused "sanitycheck: ExprOp args must have same size!" in `arg_a = ExprOp(op, *args_a)`.
=> simp_cmp_bijective_op improvement

miasm/jitter/jitcore_llvm.py, miasm/runtime/divti3.c, miasm/runtime/export.h, miasm/runtime/int_endianness.h, miasm/runtime/int_lib.h, miasm/runtime/int_types.h, miasm/runtime/int_util.h, miasm/runtime/udivmodti4.c, miasm/runtime/udivti3.c, setup.py, test/test_all.py
It's still a hack to fix the "divsion" problem with LLVM, but seems to work under Linux! (haven't tried under Windows yet but hopefully it works)
=> Include missing functions from llvm's compiler-rt into Jitllvm

miasm/jitter/jitload.py
Hi!
I added this option because I kept doing:
```
sb.jitter.set_trace_log()
sb.jitter.continue_run(step=True)
sb.jitter.set_trace_log(False, False, False)
```
And I think it's more convenient this way. What do you think ?
=> Jitter: add a trace option to 'run'

miasm/os_dep/win_api_x86_32.py
Extend the structure size to fit with the documentation : structure should be `0x44` bytes. All of these bytes should be initialized.
TODO : initialize correctly the fields of the structure, but I leave that to a future PR.
=> Fix bug in kernel32_GetStartupInfo

miasm/expression/simplifications_common.py
Hi!
`assert int(int2)` seems not to be the clearest way to prevent a division by 0. Took me some time to realize that it actually is no bug in the constant propagation engine. This PR is a proposal to be more specific here.
Best,
phrazer
=> simplifications_common: added explicit assertion messages for division by 0

miasm/os_dep/win_api_x86_32.py
When using `rfind` in Python 3, it raises a TypeError when the type of the string and the type of the character searched are different.
=> Fix type error in msvcrt_wcsrchr and msvcrt_strrchr for Python 3

example/disasm/callback.py, miasm/arch/arm/disasm.py, miasm/arch/x86/disasm.py, miasm/core/asmblock.py, test/core/asmblock.py
* Updt `dis_block_callback`, as mostly every arguments are present in the mdis engine;
* `apply_splitting` is now member of `disasm_engine` instead of `AsmCfg`: `apply_splitting` needs offsets in the asmcfg blocks, so it seems legit to need a disasm engine. Moreover, `apply_splitting` in a purely assembled asmcfg from blocks may be useless.
=> Updt dis_block_callback; apply_splitting

miasm/analysis/dse.py
to prevent TypeError during the subsequent byte object formatting
=> Bug fix - tuples need to be converted to str before using force_bytes

example/ida/graph_ir.py, miasm/analysis/modularintervals.py, miasm/arch/aarch64/arch.py, miasm/arch/msp430/arch.py, miasm/core/asmblock.py, miasm/core/locationdb.py, miasm/core/modint.py, miasm/core/utils.py, miasm/expression/expression.py, miasm/expression/simplifications_common.py, miasm/expression/simplifications_explicit.py, miasm/ir/translators/C.py, miasm/ir/translators/smt2.py, miasm/jitter/llvmconvert.py, test/core/modint.py, test/jitter/jitload.py, test/test_all.py
This PR cleans the `ExprInt` value. You now have two ways to retrieve the value of an `ExprInt`: 
- `int(expr)`
- `expr.arg`
The expr.arg is now a python `int`
Thus, the `Expression` modules does not depends on the `modint` modules, which is now moved to the `miasm.core` directory.
The `ExprInt` now only takes an integer/size as input, not a `modint`.
=> Int expr arg

miasm/core/asmblock.py
which was making the overlap check meaningless
=> output_interval was never updated and hence always empty

miasm/core/utils.py, miasm/jitter/jitload.py
Most modules were moved from the root namespace of `collections` module to `collections.abc` since Python 3.2, and will stop work as is in the next Python 3.9 https://docs.python.org/3/library/collections.html
=> Fix collections

miasm/jitter/loader/pe.py
When there are no exports, `get_export_name_addr_list` raises an exception at `miasm/jitter/loader/pe.py`, line 152:
```
AttributeError: 'DirExport' object has no attribute 'f_names'
```
Return an empty list instead.
=> Fix get_export_name_addr_list when there are no exports

miasm/jitter/vm_mngr.c, miasm/jitter/vm_mngr.h, miasm/jitter/vm_mngr_py.c
VmMngr suffers of a buffer overflow (which crashes the python interpreter) if you try to allocate a virtual memory page of size >= 4GiB.
=> Fix overflow if virtual memory page size >= 4GiB

miasm/ir/ir.py
When adding an AsmBlockBad in an IRCFG, the result was:
This was due to the add of a dummy block ir in, which was linked to an unknown `loc_key` created for the case.
The fix gives:
=> Fix lift AsmBadBlock

miasm/arch/aarch64/arch.py
Hello,
I noticed that some disassembly of ldp/stp was wrong, as the imm7 parameter is sometimes treated as unsigned as it should be always treated as signed for 'PRE' / 'POST' / 'SIGNED' classes.
Normally the 'signed' class will sign extend on the data read from mem : I didn't fix the semantic, as the 'opc' parameter seems not available when 'ldp' is called inside 'sem.py', or did I miss something?
Here is the fix at least for the disassembly, 'imm7' is always treated as signed.
Example for 'ldp', that was outputing a wrong disassembly:
```python
from __future__ import print_function
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB
instrs = b"\xA1\x83\x7C\xAD"        # LDP             Q1, Q0, [X29,#-0x70] …
```
=> [AARCH64] fix 'ldp' disas ; remove duplicate 'umsubh'

miasm/analysis/data_flow.py
Let A and B undef.
If we have:
X = [A]
X and [A] can be set in the same equivalence class (even if A and B are
undef)
=> Fix propagate undef

miasm/expression/parser.py
There is a small typo in miasm/expression/parser.py.
Should read `corresponding` rather than `corresponoding`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, corresponoding -> corresponding

setup.py
The future library is used in `miasm/core/bin_stream.py`: `from future.utils import PY3`
When running miasm (with Python 3.9.1) without future installed, I get the following error:
`ModuleNotFoundError: No module named 'future'`
I assume that future needs to be installed to run miasm (and consequently needs to be added to the dependencies). Or am I doing something wrong?
=> Add future to install_requires in setup

miasm/arch/mips32/sem.py
- Fix `sb` & `sh` instruction
- Fix m2_expr import
But there are still warnings in my editor, like this
```python
@sbuild.parse
def jal(arg1):
"Jumps to the calculated address @arg1 and stores the return address in $RA"
PC = arg1
ir.IRDst = arg1
RA = m2_expr.ExprLoc(ir.get_next_break_loc_key(instr), RA.size)
```
It warns that `ir` & `instr` are undefined. I don't know whether it can work normally with `@sbuild.parse`.
=> Fix sem.py in MIPS32

Dockerfile
The python3 version that comes with stretch does not like accented characters, `docker build .` results in:
``` pytb
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-oosab_wh-build/setup.py", line 344, in <module>
buil_all()
File "/tmp/pip-oosab_wh-build/setup.py", line 269, in buil_all
url = "http://miasm.re",
File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 272, in run
writer(self, ep.name, os.path.join(self.egg_info, ep.name))
File …
```
=> Fix Dockerfile (UnicodeEncodeError)

example/ida/utils.py
`idc.GetReg` API call is changed to `idc.get_sreg` in IDA 7.x
https://hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml
=> Updated IDA API call for IDA 7.x

miasm/jitter/vm_mngr.c
Avoid unecessary "heap pressure" during jitted code execution
=> Optimise heap manipulation for mem accesses

miasm/arch/x86/arch.py, setup.py, test/arch/x86/arch.py
Example of problem instruction `mov qword ptr es:[rax], rdx` (`26 48 48 89 10` in hex where `48` is REX prefix)
Issue: https://github.com/cea-sec/miasm/issues/1375
=> x86_64 Fix multiple REX prefix instruction disasm

miasm/arch/x86/sem.py
POP SP/ESP were broken in x64 mode.
Same for POP SP in x32 mode.
etc.
Now, we don't increment reg_sp at all if it is the target of the POP.
=> Fixed "POP reg_sp" in all modes

miasm/arch/mips32/jit.py, miasm/arch/mips32/sem.py, miasm/os_dep/linux/environment.py, miasm/os_dep/linux/syscall.py
Hello,
As mentioned in the title, this PR aims to implement a minimalist Linux environment for the mips32b architecture in order to handle syscalls.
There is also an implementation of the `socket` syscall (to give an example).
=> Implement syscall handler for mips32b + minimal Linux environment

example/asm/shellcode.py
The first argument to ArgumentParser is the program name, not the description. The previous version displayed invalid usage in the help command:
```
usage: Multi-arch (32 bits) assembler [-h] [--PE] [-e ENCRYPT ENCRYPT] architecture source output
```
The new version displays the correct usage:
```
usage: shellcode.py [-h] [--PE] [-e ENCRYPT ENCRYPT] architecture source output
Multi-arch (32 bits) assembler
```
=> Incorrect usage in shellcode.py --help

miasm/arch/x86/regs.py
Hello,
I encountered the following exception:
```
[...]
File "XXX\miasm\core\cpu.py", line 1257, in dis
ret = f.decode(todo[i])
File "XXX\miasm\arch\x86\arch.py", line 2265, in decode
expr = modrm2expr(xx, p, 1)
File "XXX\miasm\arch\x86\arch.py", line 1977, in modrm2expr
expr = size2gpregs[admode].expr[modrm_k]
IndexError: list index out of range
```
While trying to disassemble the following bytecodes : ``67 83 05 90 00 00 00 42`` (note the usage of the prefix ``0x67`` -> Address-size override prefix).
Script example to reproduce the issue:
```python
from __future__ import print_function
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB
instrs = b"\x67\x83\x05\x90\x00\x00\x00\x42"
instrs += b"\xC3"
loc_db = …
```
=> [x86] add missing Expression EIP when using address-size prefix for RIP-relative addressing

.github/workflows/tests.yml
This PR adds, in CI:
* Matrix test for Python 3.10
* use of LLVM 8 as expected by the currently used `llvmlite` version
=> CI: add support for Python 3.10

miasm/jitter/vm_mngr.h, setup.py
This still requires you have Visual Studio and LLVM installed, but might prevent some issues like #1404
This was tested with LLVM versions 4.0.0-15.0.2, 32-bit python and 64-bit python. Additionally I added support for detecting Visual Studio's Clang-cl so you don't have to install LLVM separately.
=> Allow building on Windows without a Visual Studio command prompt

setup.py
When using a `requirements.txt` like this:
```
graphviz~=0.20.1
z3-solver~=4.11.2.0
git+https://github.com/cea-sec/miasm@2b6c894aee49218bf8809531263a50b71a145405#egg=miasm
```
Running `pip install -r requirements.txt` will error because the `build` directory doesn't exist. This fixes that by creating the build directory if it doesn't exist yet.
=> Create the build directory to fix `pip install` build

.appveyor.yml, .github/workflows/tests.yml
It would be nice if Miasm could slowly migrate to more modern python (f-strings, type annotations). According to earlier discussions 2.7 isn't supported anymore so I took the liberty to remove it from CI.
Also a discussion about the minimal Python 3 version would be good. There's nice updates to typing in more recent versions.
=> Remove Python 2.7 from CI

example/symbol_exec/symbol_exec.py, test/test_all.py
Following the series of `dis_binary.py` and `dis_binary_lift*.py`, this PR adds a simple example to demonstrate `SymbolicExecution`:
```
$ python symbol_exec.py mystere_sub --address mystere1
Modified registers:
zf                 = ESP == 0x4
nf                 = (ESP + 0xFFFFFFFC)[31:32]
pf                 = parity((ESP + 0xFFFFFFFC) & 0xFF)
cf                 = ((((ESP + 0xFFFFFFF4) ^ (ESP + 0xFFFFFFFC)) & ((ESP + 0xFFFFFFF4) ^ 0xFFFFFFF7)) ^ (ESP + 0xFFFFFFF4) ^ (ESP + 0xFFFFFFFC) ^ 0x8)[31:32]
of                 = (((ESP + 0xFFFFFFF4) ^ (ESP + 0xFFFFFFFC)) & ((ESP + 0xFFFFFFF4) ^ 0xFFFFFFF7))[31:32]
af                 = ((ESP + 0xFFFFFFF4) ^ (ESP + 0xFFFFFFFC) ^ 0x8)[4:5]
EAX                = @32[ESP + 0x4] + @32[ESP + 0x8] + 0x1337
ECX                = -@32[ESP + 0x4] + -@32[ESP + …
```
=> Example: add a basic symbol_exec example

example/symbol_exec/depgraph.py, miasm/analysis/depgraph.py
This PR simplify the process of calling `Depgraph` by providing a util to easily retrieve the line and the loc_key of a given assembly address.
=> Depgraph: add `.address_to_location` to help find the line and loc of an address

example/jitter/unpack_generic.py, miasm/jitter/loader/pe.py, test/test_all.py
This PR adds:
- a `ImpRecStrategy` object using a FSM to recover import table in memory using a naive strategy (null-byte terminated continuation of same module export addresses)
- an example, `unpack_generic.py` using this strategy before dumping with `vm2pe`
This example is running the sandbox until it can't no more (exception, unknown API, etc.). It is very likely the OEP is not the address where it stopped, but it could be either a wave or close to the OEP. That way, dumping the binary at this state could a good way to obtain a binary which can be analyzed.
If the user is using a trace, such as `-b` and found a candidate OEP, it can stop the execution using the `--oep` argument.
For instance:
```bash
$ python unpack_generic.py ../samples/box_upx.exe -b -o
...
POPAD      
LEA …
```
=> Generic import recovery (cheap ImpRec style)

miasm/runtime/int_lib.h
Hello! I am unsure if it was intentional not to target Cygwin, but based on what the modified line was targeting, it appears the line is attempting to detect compilation environments. Cygwin is a Windows-based Unix-like POSIX environment. So while it compiles on Windows (i.e.. `defined(_WIN32)`, for MSVC), it ultimately gets compiled with Unix tools like GCC or Clang on a Windows environment, and can be detected with the `__CYGWIN__` preprocessor define.
Compilation of the C Python bindings for miasm fails because it does not detect the Cygwin environment on compilation. The fix is pretty simple. Miasm is working great on my system now.
Let me know if it was intentional not to target Cygwin, I can see why you might not want to have so many platforms to support on your plate, but if you're …
=> fix compilation on cygwin

.gitignore, example/jitter/unpack_generic.py, miasm/__init__.py, miasm/analysis/debugging.py, miasm/analysis/dse.py, miasm/arch/aarch64/sem.py, miasm/arch/x86/arch.py, miasm/core/cpu.py, miasm/core/graph.py, miasm/core/sembuilder.py, miasm/core/utils.py, miasm/expression/expression.py, miasm/expression/expression_helper.py, miasm/expression/simplifications_common.py, miasm/ir/ir.py, miasm/ir/translators/z3_ir.py, miasm/jitter/loader/pe.py, miasm/jitter/loader/utils.py, miasm/loader/minidump.py, miasm/os_dep/linux/environment.py, miasm/os_dep/win_api_x86_32.py, test/analysis/depgraph.py, test/arch/mep/asm/ut_helpers_asm.py
The main issue is the removal of the deprecated `imp` module (I replaced it with `importlib.util` and matched the existing behavior).
Other than that I made a few minor fixes of warnings, most notably fixing some broken regular expressions by switching to regex literals.
=> Python 3.12 support

example/jitter/memory_breakpoint.py
Fixes misleading format saying displaying decimal values instead of hexadecimal for `jitter.pc`
Using 0x%x everywhere for consistency.
=> Fix display format for jitter breakpoint example

miasm/arch/arm/arch.py, miasm/arch/arm/sem.py, test/arch/arm/arch.py, test/arch/arm/sem.py
This partially addresses #1456
- Moves rrx computation inside the functions, this allows to do the carry flag computation related to RRX
- Adds a shifter/rotate template for the carry flag similar to the one in x86
It is still (at least) left to:
- compute the carry flag of some instructions with immediates.
Here is an example A32ExpandImm_C (https://developer.arm.com/documentation/ddi0597/2023-06/Shared-Pseudocode/aarch32-functions-common?lang=en#impl-aarch32.A32ExpandImm_C.2). Used by ANDS, BICS, EORS, MOVS, MVNS, ORRS, TEQ, TST with immediates.
The equation is something like `cf= ROR(zExt32(imm[0:8], imm[8:12] << 1).MSB()` (if `2*imm[8:12] != 0`). This is tricky because the semantics don't know the rotate amount that was used. Maybe the additional_info object on instructions could …
=> [ARM] compute cf for shift/rotate

setup.py
Faced with installation error on Windows, last lines in exception log:
`File "C:\Users\...\AppData\Local\Temp\tmp87tpzffd\.venv\lib\site-packages\setuptools\_core_metadata.py", line 136, in write_pkg_info
self.write_pkg_file(f)
File "<string>", line 420, in _write_pkg_file
File "C:\Users\...\AppData\Local\Temp\tmp87tpzffd\.venv\lib\site-packages\setuptools\_core_metadata.py", line 210, in write_pkg_file
file.write("\n%s" % long_description)
File "C:\Python310\lib\tempfile.py", line 483, in func_wrapper
return func(*args, **kwargs)
File "C:\Python310\lib\encodings\cp1251.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe9' in position 20918: character maps to <undefined>`
I realized that …
=> Fixing error with installation on windows with cp1251

miasm/jitter/vm_mngr.h
Fixes https://github.com/cea-sec/miasm/issues/1469
test run:
```
[alex@bsd14 ~/miasm]$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/alex/miasm
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting future (from miasm==0.1.5.dev49)
Using cached future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting pyparsing>=2.4.1 (from miasm==0.1.5.dev49)
Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Using cached future-1.0.0-py3-none-any.whl (491 kB)
Building wheels for collected packages: miasm
Building wheel for miasm (pyproject.toml) ... done
Created wheel for miasm: …
```
=> Fix compilation for FreeBSD OS

test/jitter/jitcore.py
ref to issue #1500 for details
the added code makes the negative values  unsigned integers (64 or 32 bit) thus allowing to set it into uint64_t value of RAX/EAX
=> Fixes #1500

miasm/expression/expression.py, test/expression/expression.py
`__div__` is not bound to the division operator in Python3. This leads to an error when trying to divide expressions.
=> fix expression division

miasm/arch/aarch64/arch.py, test/arch/aarch64/arch.py
This fixes a typo in the decoding of `aarch64_immhi_page`.
I assume this code was copied from `aarch64_immhip_page` and someone forgot to change the shift afterwards.
The value `524020` (and immlo.value `0`) decodes to `ExprInt(0xFFFFFFFFFFFFFAC8, 64)`.
Before it would fail to re-encode this due to incorrectly assuming an overflow (`v > (1 << 19) - 1`).
After the change it re-encodes back to `524020`.
---
Fixes #1495.
=> Fix typo in aarch64_immhi_page decode

miasm/core/bin_stream.py
`bin_stream::get_u8` supposed to be returning an int.
but instead it returns a bytes object
> Not sure how the dependent callers are expecting!
=> Fix: `bin_stream::get_u8` method returning bytes

miasm/arch/aarch64/arch.py, miasm/arch/arm/arch.py, miasm/arch/x86/arch.py, miasm/core/graph.py, miasm/core/utils.py, miasm/ir/ir.py
Brackets are now escaped to comply xdot parsing
=> Fix xdot output
